### ISSUE TITLE
Unable to import monitor

### ISSUE THREAD

**Issue by taiidani** [terraform-providers/terraform-provider-datadog#10]
### Terraform Version

v0.9.9

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_monitor

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior

The state file should have been modified with the imported `requests_not_being_served` monitor.

### Actual Behavior

```
datadog_monitor.requests_not_being_served: Importing from ID "2395212"...
Error importing: 1 error(s) occurred:

* datadog_monitor.requests_not_being_served (import id: 2395212): import datadog_monitor.requests_not_being_served (id: 2395212): json: cannot unmarshal string into Go struct field Options.evaluation_delay of type int
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Datadog monitor that watches metrics.
2. `terraform import datadog_monitor.example <ID of monitor>`

**Comment by grubernaut** [comment]
Hey @taiidani, thanks for the issue! 

Looks like this is a known issue at the API and SDK levels.
Source issue: https://github.com/zorkian/go-datadog-api/issues/111

**Comment by taiidani** [comment]
Thanks! And looking through that issue, the problem is actually bigger than I thought. If DD's web UI is the source of the strings, then it can even corrupt existing monitors that were created by Terraform. Just simply open up the created monitor in DD and save it.

Once that happens it basically blows up your state file -- any time the resources are refreshed the DD API sends back that string and halts the process.

Yikes!

**Comment by bshelton229** [comment]
This should be fixed now. Datadog has fixed `evaluation_delay` to always be an INT.

**Comment by grubernaut** [comment]
@taiidani, can you confirm? Once confirmed, we can close this issue :smile: 
Thanks @bshelton229!

**Comment by taiidani** [comment]
Confirmed! Imported an existing monitor made from the Web UI, and successfully plan+applied back to Datadog.
