### ISSUE TITLE
datadog_screenboard issues (legend_size, conditional_format.color)

### ISSUE THREAD

**Issue by michalschott** [terraform-providers/terraform-provider-datadog#104]
### Terraform Version
0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_screenboard

### Terraform Configuration Files
```hcl
resource "datadog_screenboard" "dev_monitor" {
  title = "Terraform Test Dashboard"

  template_variable {
    name    = "k8s_state_namespace"
    prefix  = "namespace"
    default = "namespace:int"
  }

  template_variable {
    name    = "kube_namespace"
    prefix  = "kube_namespace"
    default = "kube_namespace:int"
  }

  template_variable {
    name    = "k8s_state_deployment"
    prefix  = "deployment"
    default = "*"
  }

  template_variable {
    name    = "kube_deployment"
    prefix  = "kube_deployment"
    default = "*"
  }

  widget {
    type        = "query_value"
    x           = 0
    y           = 0
    height      = 14
    width       = 16
    title       = "Desired pods"
    title_size  = 16
    title_align = "left"

    time {
      live_span = "5m"
    }

    tile_def {
      viz       = "query_value"
      autoscale = true
      precision = 0

      request {
        q          = "sum:kubernetes_state.deployment.replicas_desired{$k8s_state_namespace,$k8s_state_deployment}"
        type       = "null"
        aggregator = "avg"

        style {
          palette = "dog_classic"
          type    = "solid"
          width   = "normal"
        }

        conditional_format {
          palette    = "custom_text"
          value      = "0"
          color      = "#6a53a1"
          comparator = ">"
        }
      }
    }
  }
}
```

### Expected Behavior
Widget should use #6a53a1 color in conditional format.

### Actual Behavior
Color is set to #000000

### Steps to Reproduce
1. `terraform apply`
2. Adjust colour by editing the widget
3. `terraform plan` will show:
```hcl
  ~ datadog_screenboard.dev_monitor
      widget.0.legend_size:                                     "0" => ""
      widget.0.tile_def.0.request.0.conditional_format.0.color: "" => "#6a53a1"
```

**Comment by nmuesch** [comment]
Hey @michalschott thanks for the issue report and apologies for the delay here. We just merged in this fix in the go api client - https://github.com/zorkian/go-datadog-api/pull/260. The next go client release should include this, and once we bump that dependency here, this should work without any changes required. 

In addition to that, the new Dashboards resource was released recently that includes support for this and some further validations. More documentation on that can be found here - https://www.terraform.io/docs/providers/datadog/r/dashboard.html#custom_fg_color

I'll go ahead and close this issue for now but let me know if you continue to experience any issues with this.
