### ISSUE TITLE
Cannot use vault credentials for this provider

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-datadog#111]
Discussion initially in this thread https://github.com/terraform-providers/terraform-provider-vault/issues/219

### Terraform Version
0.11.10

### Affected Resource(s)
datadog `provider` block

### Terraform Configuration Files
```hcl
provider "vault" {
  address = "https://vault.mycompany.com"
}

data "vault_generic_secret" "datadog_api" {
  path = "secret/datadog/provisioning/api"
}

data "vault_generic_secret" "datadog_app" {
  path = "secret/datadog/provisioning/app"
}

provider "datadog" {
  api_key = "${data.vault_generic_secret.datadog_api.data.value}"
  app_key = "${data.vault_generic_secret.datadog_app.data.value}"
}
```

### Expected Behavior
The terraform above should allow me to login with my vault credentials.

### Actual Behavior
Datadog provider initialization runs before all the data sources complete forcing users to use the api and app keys directly in terraform or provide them as inputs.

### Steps to Reproduce

1. `terraform init && terraform plan`

**Comment by bkabrda** [comment]
This seems to be working for me with TF 0.11.13, Vault provider 1.7.0 and Datadog provider 1.7.0. Can you still reproduce this @nitrocode? If so, could you post versions of the Vault and Datadog providers and also the exact error you're getting? A debug log (use env variable `TF_LOG=debug`) would also be useful, but you'd have to be *very* careful to remove the actual secrets from that.

**Comment by nmuesch** [comment]
Hey @nitrocode 👋 Just wanted to follow up on the note @bkabrda left and see if you were still hitting this issue?

**Comment by nitrocode** [comment]
Yes @nmuesch

**Comment by nitrocode** [comment]
@nmuesch I'll double check. thank you for following up!

**Comment by nmuesch** [comment]
Hey @nitrocode Just wanted to reach back out here. Were you still encountering this issue?

**Comment by nitrocode** [comment]
Works! Thank you
