### ISSUE TITLE
datadog_screenboard - widget swapping `x` and `y` parameters

### ISSUE THREAD

**Issue by sudomateo** [terraform-providers/terraform-provider-datadog#119]
### Terraform Version
```
$ terraform -v
Terraform v0.11.10
+ provider.datadog v1.5.0
```

### Affected Resource(s)
- `datadog_screenboard`

### Terraform Configuration Files
```hcl
resource "datadog_screenboard" "example" {
  title     = "Test Screenboard"
  read_only = false

  widget {
    type       = "note"
    x          = 30
    y          = 5
    bgcolor    = "pink"
    text_align = "right"
    font_size  = "36"
    tick       = true
    tick_edge  = "bottom"
    tick_pos   = "50%"
    html       = "<b>test note</b>"
  }
}
```

### Debug Output
[https://gist.github.com/sudomateo/65ff1e0d3fd20b7aa73abc04714e522f](https://gist.github.com/sudomateo/65ff1e0d3fd20b7aa73abc04714e522f)

### Panic Output
N/A

### Expected Behavior
The resource should create the widgets in the screenboard at the correct `x` and `y` coordinates on the screenboard grid.

### Actual Behavior
Terraform seems to be swapping the `x` and `y` values for the screenboard widgets.

### Steps to Reproduce
1. Create the `main.tf` with the content above.
2. Run `terraform init` to download the Datadog provider plugin.
3. Run `terraform plan` to verify the plan output.
4. Run `terraform apply` to apply the plan. Enter `yes` when prompted.
5. Note the values Terraform inserts for the `x` and `y` parameters for the widgets.
6. Note the ID of the screenboard.
7. Check the location of the widget in the Datadog web UI. Note how the widget is not at the proper `x` and `y` locations but instead at the swapped location.
8. Query the Datadog API using `curl -X GET "https://api.datadoghq.com/api/v1/screen/${DATADOG_SCREENBOARD_ID}?api_key=${DATADOG_API_KEY}&application_key=${DATADOG_APP_KEY}"`
9. Note how the `x` and `y` values queried from the API are swapped from what Terraform reported.

### Important Factoids
I have tested this using `curl` and with the Datadog Python API client.

### References
N/A

**Comment by masci** [comment]
This is fixed on `go-datadog-api` master, see https://github.com/zorkian/go-datadog-api/pull/190, we'll be able to ship it in the next release.

**Comment by sudomateo** [comment]
@masci beautiful! Thanks for pointing out the API client fix. I didn't see it when I was poking around in that repo.
