### ISSUE TITLE
Convert user role field to a computed field

### ISSUE THREAD

**Issue by Nowaker** [terraform-providers/terraform-provider-datadog#12]
"role" cannot be changed once a user is in the system. Once it's created and role has changed in the meantime, `terraform plan` will always suggest changing the role. However, `terraform apply` won't change anything, and subsequent `terraform plan` will want to change the role again. If it's not possible to change one's role via API, it's better to convert this field as computed so it doesn't complicate things.

```
~ datadog_user.datadog_user_rush
    role: "" => "Lead Channel Engineer"
```

**Comment by nyanshak** [comment]
I was going to try to fix this somehow but I'm wondering if the API has changed for users.

When I do a POST (to create user), passing in:
```
{
  "role": "test role",
  "email": "test@example.com",
  "handle": "test@example.com",
  "name": "test user",
  "access_role": "st"
}
```
I'm still getting back a user object with role set to null. On PUTs with role set to some value, I still get back a null role.

I've done this with a new trial account with the admin keys. I've reached out to Datadog support to understand what the behavior should be.

**Comment by masci** [comment]
I'm investigating internally what the behaviour of `role` should be, the UI has the same issue.

**Comment by masci** [comment]
`role` isn't supported anymore, going to deprecate the corresponding argument.
