### ISSUE TITLE
Errors coming up on unmodified dashboards after upgrading TF to new version: json: cannot unmarshal number into Go struct field GraphDefinition.precision of type string

### ISSUE THREAD

**Issue by andrealiz** [terraform-providers/terraform-provider-datadog#136]
Hi there,

I've upgraded to new TF version and have since experienced errors on dashboards that haven't been modified since last year. I have reviewed the files that it listed where errors occurred and can confirm that variables are being called from correct module files. We are also just using strings. The error message is as follows:

> json: cannot unmarshal number into Go struct field GraphDefinition.precision of type string

Should I revert back to an older version? I previously had v0.11.07

### Terraform Version
Terraform v0.11.11
+ provider.datadog v1.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_timeboard

### Expected Behavior
List modifications of dashboards

### Actual Behavior
Threw an error for old and unmodified dashboards. Could not complete terraform plan.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by AlexJF** [comment]
This is probably related to some breaking changes in the API and is likely fixed by upgrading `provider.datadog` to 1.6.0 which includes https://github.com/terraform-providers/terraform-provider-datadog/pull/127

**Comment by andrealiz** [comment]
Thank you @AlexJF ! this cleared the error for me and I'm now seeing the expected behavior.
