### ISSUE TITLE
Support for Synthetics (external monitoring)

### ISSUE THREAD

**Issue by dharada1** [terraform-providers/terraform-provider-datadog#147]
Requesting support for Synthetics. (external monitoring)

<img width="1625" alt="2019-01-25 11 24 31" src="https://user-images.githubusercontent.com/6387224/51721667-18840800-2096-11e9-9535-4d08413affa9.png">

**Comment by dasch** [comment]
Yes please!

**Comment by lc-nyovchev** [comment]
Yes, especially when Synthetics is out of Beta, please!

**Comment by tavisma** [comment]
+1

**Comment by mwarkentin** [comment]
Synthetics is now GA, would be nice if it was supported!

https://www.datadoghq.com/blog/introducing-synthetic-monitoring/

**Comment by btoueg** [comment]
Hey! I'm from Datadog Synthetics team and we're happy about the enthusiasm around the Terraform support 🎉 
As a heads up, we plan on working on it soon. Can't give you any date, but it's quite high on our feature requests!

**Comment by kareemstraker-wk** [comment]
Hi, hoping we can get this added.
I would really like to see this. 👍

**Comment by jbanton-dm** [comment]
Looks like it's supported now. The documentation for assertions is missing some options. I see at least `lessThan` missing.

**Comment by bkabrda** [comment]
Yes, synthetics is now supported: https://www.terraform.io/docs/providers/datadog/r/synthetics.html

@btoueg could you look into the missing assertion options mentioned by @jbanton-dm before we get this issue closed? Thanks!

**Comment by micheletest** [comment]
This is great, thanks! I was able to use this yesterday for an api monitor. 

A few comments/suggestions:

1. It would be nice to provide a link to DD documentation for locations from here: https://www.terraform.io/docs/providers/datadog/r/synthetics.html#locations

2. I wasn't exactly sure how to implement a browser synthetics from the doc. Can a more detailed example be included? In particular a browser test with multiple steps and assertions would be really helpful.

**Comment by bkabrda** [comment]
So #180 has fixed all the requests for doc improvements, hence I'm closing this issue. If you find any more gaps, feel free to open a new issue. Thanks everyone!
