### ISSUE TITLE
Support graph groups in timeboards

### ISSUE THREAD

**Issue by dpiddockcmp** [terraform-providers/terraform-provider-datadog#156]
Please add support for graph groups in the timeboard resource.    

### Terraform Version
Terraform v0.11.11
+ provider.datadog v1.6.0

### Affected Resource(s)
`datadog_timeboard`

**Comment by bkabrda** [comment]
Hey, would it be possible for you to start using the new `datadog_dashboard` resource, which has a `group_definition` feature? Example at https://www.terraform.io/docs/providers/datadog/r/dashboard.html

**Comment by dpiddockcmp** [comment]
Yes, the new `datadog_dashboard` solves this particular issue.

Unfortunately dashboard still doesn't have feature parity with the old timeboard. So I'm stuck in the middle. See #275 and #276 for example. Looks like they're coming soon 😄 

I'll close this.

**Comment by bkabrda** [comment]
Yeah, we'll be expanding the functionality of the new dashboard resource in the near future to solve these issues. If you have any more specific examples of where it is lacking, please do open new issues and we'll see what we can do about them.
