### ISSUE TITLE
Silence config block not recognizing variable

### ISSUE THREAD

**Issue by masonbivens** [terraform-providers/terraform-provider-datadog#159]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
`Terraform v0.10.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_monitor (silenced config block)

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "lambda_throttled_invocations" {
  name = "[${upper(var.env)}] Lambda Throttled Invocations - {{functionname.name}}"
  type = "metric alert"

  query = "sum(last_30m):avg:aws.lambda.throttles{awsenv:${var.env}} by {functionname,product,team}.as_count() > 300"

  notify_no_data = false
  include_tags   = true
  locked         = true

  evaluation_delay = 900

  thresholds {
    warning           = 100
    warning_recovery  = 50
    critical          = 300
    critical_recovery = 200
  }

  message = <<EOM
${var.datadog_managed_by}

{{#is_alert}}Current Throttle Rate {{value}} has crossed the threshold {{threshold}}. Please investigate the issue{{/is_alert}}
{{#is_warning}}Current Throttle Rate {{value}} has crossed the warning threshold {{warn_threshold}}{{/is_warning}}
${var.datadog_alert_footer}
@slack-aws-alerts
EOM

  silenced {
    "functionname:app-report-generator-${var.env}" = 0
  }

  tags = ["service:lambda", "env:${var.env}", "managed_by:terraform"]
}
```
### Expected Behavior
The silenced functionname should be rendered like `"functionname:app-report-generator-dev" = 0`

### Actual Behavior
The silenced functionname is rendered as `"functionname:app-report-generator-${var.env}" = 0`

### Important Factoids
We are currently generating environment isolated monitors. The variables are rendered everywhere else in the resource, but they don't appear to work in the silenced block.

**Comment by bkabrda** [comment]
The issue here is not with the datadog provider, but with HCL, which doesn't support interpolation in key values [1]. A workaround for this is using the `map` function, so you'd need to do something like `silenced = ${map("functionname:app-report-generator-${var.env}", 0)}`.

I'll see if there's a good place in the provider documentation where this could be added as a note.

[1] https://github.com/hashicorp/terraform/issues/2042
