### ISSUE TITLE
downtime: no access to `monitor_tags` propery

### ISSUE THREAD

**Issue by vanvlack** [terraform-providers/terraform-provider-datadog#162]
### Terraform Version

```
Terraform v0.11.12
+ provider.aws v2.0.0
+ provider.datadog v1.7.0
+ provider.external v1.0.0
+ provider.template v2.1.0

Your version of Terraform is out of date! The latest version
is 0.11.13. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

`datadog_downtime`

### Terraform Configuration Files
```hcl
resource "datadog_downtime" "business_hours_weekday_morning" {
  scope        = ["*"]
  monitor_tags = ["a_tag:here"]
  message      = "business hours evening downtime - `00:00` to `09:00` Central"

  start_date = "2019-03-12T05:00:00Z"
  end_date   = "2019-03-12T14:00:00Z"

  recurrence {
    type      = "weeks"
    period    = 1
    week_days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
  }

  lifecycle {
    ignore_changes = ["start_date", "end_date"]
  }
}
```

### Debug Output

https://gist.github.com/vanvlack/c334632cbd5120c17678f2e20d3a6571

### Expected Behavior

Allow access to the `monitor_tags` property

### Actual Behavior

The property isn't accessible via the datadog provider

### Steps to Reproduce

1. `terraform apply`

### References

https://docs.datadoghq.com/api/?lang=bash#schedule-monitor-downtime

```
monitor_tags [optional, default=no monitor tag filter]: A comma-separated list of monitor
tags, i.e. tags that are applied directly to monitors, not tags that are used in monitor
queries (which are filtered by the scope parameter), to which the downtime applies.
The resulting downtime applies to monitors that match ALL provided monitor tags
(i.e. service:postgres AND team:frontend), NOT any of them.
```

**Comment by kevinahlstrom** [comment]
Great timing.   I was just trying to use monitor tags.

My use case is I have a situation where 4 monitors are monitoring one application and I have to create 4 different schedules for it.  

It would be nice to consolidate to one downtime schedule.  Right now I really don't want to use notifications to let people know these schedules exist because of the inability to consolidate it to one notification.  

There are workarounds, this would be a nice feature addition.

**Comment by vanvlack** [comment]
submitted changes to the client for this: https://github.com/zorkian/go-datadog-api/pull/227

**Comment by vanvlack** [comment]
This is complete, as of #167 i believe, any reason to keep it open @bkabrda

**Comment by bkabrda** [comment]
You're right @vanvlack, I'm closing it. Thanks for the ping!
