### ISSUE TITLE
Integration Monitor type mission in datadog_monitor

### ISSUE THREAD

**Issue by rsun-thoughtworks** [terraform-providers/terraform-provider-datadog#177]
Hi according to datadog_monitor docs [https://www.terraform.io/docs/providers/datadog/r/monitor.html#type]()

`Integration Monitor` is not a supported type. However, datadog can create `Integration Monitor` monitor.

Could you please help us and support `Integration Monitor` type. Or is there any work around?

Thanks.

**Comment by bkabrda** [comment]
I believe that Integration Monitor is actually called "query monitor" when creating through API as listed in the table at https://docs.datadoghq.com/api/?lang=python#monitors - could you try using that?

**Comment by rsun-thoughtworks** [comment]
> I believe that Integration Monitor is actually called "query alert" when creating through API as listed in the table at https://docs.datadoghq.com/api/?lang=python#monitors - could you try using that?

Thanks, I will have a try.

I will leave a message if it works.

**Comment by nmuesch** [comment]
Hey @rsun-thoughtworks the type you're looking for will depend on what kind of integration monitor you're trying to create. A metric based monitor will be type `query alert` while a service check monitor will have type `service check`. Both the Datadog API documentation page and the terraform provider docs were just updated to help better reflect this - https://github.com/terraform-providers/terraform-provider-datadog/pull/213.

I'll go ahead and close out this issue but please let us know if you continue to have any issues with this!

**Comment by uriinf** [comment]
Confirmed. Integration monitor "service check" works:
```hcl
resource "datadog_monitor" "this" {
  name               = "Solr can connect on {{host}}"
  type               = "service check"
  message = "Solr isn't accessible on  {{host}} 3  @alerts"
  query = "'solr.can_connect'.over('monitored:true').by('host').last(4).count_by_status()"
  thresholds = {
    critical          = 3
    ok                = 1
  }
}
```
