### ISSUE TITLE
Feature request: Please support the new SLO widget on screenboards

### ISSUE THREAD

**Issue by micheletest** [terraform-providers/terraform-provider-datadog#179]
I am excited about the new SLO widget. It would be great to include that widget type datadog_screenboard in terraform. https://www.datadoghq.com/blog/slo-monitoring-widget/

### Terraform Version
`Terraform v0.11.10`

### Affected Resource(s)
https://www.terraform.io/docs/providers/datadog/r/screenboard.html#type

### Terraform Configuration Files
would like to have an `slo` type for screenboards

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Please add support for this.

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
N/A

**Comment by platinummonkey** [comment]
👋 There are a number of changes coming up for SLI/SLO's in datadog, including how this widget works. This widget is still in `beta` and the configuration will actually be moving to it's own centralized management, along with specific API's.

**Comment by hirenshah005** [comment]
Is there any update here? I am planning to use this in TF 0.12

**Comment by platinummonkey** [comment]
👋 none :) though stay tuned for https://www.dashcon.io/workshops/ 😉

**Comment by micheletest** [comment]
Was anything announced regarding this at dashcon? I didn't make the SLO workshop and don't see it in the Dash writeup.

**Comment by platinummonkey** [comment]
Posting here for people watching this thread:
go-client PR https://github.com/zorkian/go-datadog-api/pull/250
tf updates (needs the above to be merged first): https://github.com/terraform-providers/terraform-provider-datadog/pull/263

In the meantime the team is working on a number of improvements for SLO widget on dashboards + the new SLO views.

**Comment by ludov04** [comment]
The terraform support is great but I get 
```
{"errors": ["SLO management not found”]}
```
when trying to create a widget, is it still in closed beta at datadog ?

**Comment by platinummonkey** [comment]
@ludov04 for now yes, though stay tuned to our Summit annoucements next week :)

**Comment by platinummonkey** [comment]
this was announced as publicly available at our summit last week 🎉 @ludov04 

As for the widget, we will be releasing an updated version of that shortly and migrating existing widgets (stay tuned 😄)

**Comment by 0x646e78** [comment]
Looks like this has been added in now, from https://github.com/terraform-providers/terraform-provider-datadog/pull/355 . Any ideas when a new release will be available?

**Comment by 0x646e78** [comment]
I'm so curious as to when a release will be made of this provider now. Pretty keen on having this without pulling from github.

**Comment by platinummonkey** [comment]
I've pinged the team internally about cutting a new release :)

**Comment by gzussa** [comment]
Closing this since we are cutting a release.
