### ISSUE TITLE
Feature Request: Support `yaxis` field in screenboard widget

### ISSUE THREAD

**Issue by charlesverdad** [terraform-providers/terraform-provider-datadog#188]
The `yaxis` parameter is supported in `datadog_timeboard.graph` but not in `datadog_screenboard.widget`.

**Comment by nmuesch** [comment]
Hey @charlesverdad We just released version 2.1.0 of the Datadog Terraform Provider which includes the new Dashboard resource! This resource includes the support for yaxis in different widget types. Does this address your use case - https://www.terraform.io/docs/providers/datadog/r/dashboard.html

**Comment by charlesverdad** [comment]
Yes, this is exactly what I needed. Thanks!
