### ISSUE TITLE
Underscores are not preserved in column names

### ISSUE THREAD

**Issue by moosamus** [terraform-providers/terraform-provider-datadog#192]
### Terraform Version
```
terraform -v

Terraform v0.11.13
+ provider.aws v2.9.0
+ provider.datadog v1.8.0
+ provider.template v2.1.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_screenboard

### Terraform Configuration Files
```hcl
resource "datadog_screenboard" "service_screenboard" {
  title     = "dev-service screenboard"
  read_only = true

  widget {
    type    = "log_stream"
    width   = 100
    height  = 0
    x       = 0
    y       = 50
    query   = "service:elb dev-service"
    columns = "[\"@http.status_code\",\"@http.url_details.path\"]"
  }
}
```

### Debug Output
https://gist.github.com/moosamus/03e77f8aeccbb017ac97233c36219a39

### Panic Output
None

### Expected Behavior
The log_stream widget should have columns with the supplied names

### Actual Behavior
Underscores are stripped, at least partially. `@http.status_code` becomes `code` and `@http.url_details.path` becomes `details_path`. It also cannot be escaped predictably (at least by me)

![datadog_underscores](https://user-images.githubusercontent.com/587033/57251654-54752480-7018-11e9-811c-dabe58101875.jpeg)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
None

**Comment by nmuesch** [comment]
Hey @moosamus Thanks for the issue report. I've raised this internally to the appropriate team and a longer term fix is being worked on on the API side of things to support the `@` character in the columns field.

As a workaround, you can replace `@` with `log_` to submit this field as expected. I'll go ahead and close this issue for now as we are tracking a longer term solution. Thanks again for the report!

**Comment by moosamus** [comment]
Good to know, thanks!
