### ISSUE TITLE
Provider version 1.8.0 cleans access_role if not explicitly set

### ISSUE THREAD

**Issue by kdubmartins** [terraform-providers/terraform-provider-datadog#197]
### Terraform Version
terraform `0.10.8`
datadog provider version `1.8.0`

### Affected Resource(s)
- datadog_user.user

### Terraform Configuration Files
```hcl
resource "datadog_user" "user" {
  email    = "${var.username}@domain.com"
  handle   = "${var.username}@domain.com"
  name     = "${title(element(split(".", var.username),0))} ${title(element(split(".", var.username),1))}"
  disabled = "${local.disabled}"
  is_admin = "${local.admin}"
}
```
### Expected Behavior
A `terraform plan` should not touch unmodified properties.

### Actual Behavior
A `terraform plan` shows that every user's `access_role` property will be changed from whatever it is (can be `adm` or `st`) to an empty string `""`.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
- Version 1.7.0 does not show this behavior.
- If I try to replace the deprecated `is_admin` flag by `access_role`, a terraform plan shows that all users with `is_admin = true` will be set to **false**, but doesn't show any changes to the access_role flag, confusing me if it's harmful or not.
```hcl
// is_admin = "${local.admin}"
access_role = "${local.admin ? "adm" : "st"}"
```
- If I leave both flags active, terraform plans just fine. Shouldn't the flags conflict?

**Comment by kdubmartins** [comment]
I tested applying the change below to my admin account. 
```hcl
~ module.user.datadog_user.user
    is_admin:   "true" => "false"
```
It didn't change my permissions (I'm still admin) probably because `access_role` flag is having priority, which is good, but the change continues to appear if I plan again. 

Please note that the `is_admin` flag is **not** present in the code anymore. 
```hcl
resource "datadog_user" "user" {
  email       = "${var.username}@domain.com"
  handle      = "${var.username}@domain.com"
  name        = "${title(element(split(".", var.username),0))} ${title(element(split(".", var.username),1))}"
  disabled    = "${local.disabled}"
  access_role = "${local.admin ? "adm" : "st"}"
}
```

**Comment by nmuesch** [comment]
Hey @kdubmartins Sorry for the delay here, thanks for reporting the issue. 

The is_admin flag is currently being deprecated and unfortunately currently has the effect of creating a diff in the plan as noted here - https://www.terraform.io/docs/providers/datadog/r/user.html#argument-reference

If not set, access role should have a default of `st`, are you still seeing this default to an empty string?

**Comment by kdubmartins** [comment]
Hi @nmuesch, thanks for the response.
No, I don't see access_role default to an empty string anymore.
Thanks.

**Comment by nmuesch** [comment]
Thanks for the confirmation. I'll go ahead and close this issue in that case, but please do let me know if you have any further issues with this! Thanks again for the detailed issue report.
