### ISSUE TITLE
Feature request: support for provisioning of DD monitor type "network"

### ISSUE THREAD

**Issue by krupnikola** [terraform-providers/terraform-provider-datadog#208]
As per documentation: https://www.terraform.io/docs/providers/datadog/r/monitor.html#type

provisioning of Datadog monitors of type `network` is not supported ATM.

Datadog docs: https://docs.datadoghq.com/monitors/monitor_types/network/

Please care to comment if this can be added to the provider, thanks.

**Comment by bkabrda** [comment]
Hi, as per the API documentation [1], the `network` monitor is specified as `service check` to the API (and thus also to the provider), so this should work if you use `service check`. It is true that this is somewhat confusing, so I'll keep this issue open to get this section improved in the provider documentation.

Let me know if this doesn't work for you as expected.

[1] https://docs.datadoghq.com/api/?lang=python#create-a-monitor

**Comment by nmuesch** [comment]
Hey @krupnikola 👋 As @bkabrda mentioned, you should be able to use the type `service check`. We've just merged in some extra documentations surrounding this type mapping - https://github.com/terraform-providers/terraform-provider-datadog/pull/213, so I'll go ahead and close this issue out for now. Though please do let us know if you continue to hit any issues with this!
