### ISSUE TITLE
Support new dashboard API

### ISSUE THREAD

**Issue by lexrj** [terraform-providers/terraform-provider-datadog#211]
Hi there,

### Terraform Version
11+

### Affected Resource(s)
- datadog_screenboard
- datadog_timeboard

### Expected Behavior
Datadog API has deprecated the screenboard and timeboard APIs in favor of a unified dashboard API: https://docs.datadoghq.com/api/?lang=bash#dashboards

I would expect the provider to match in this regard. This covers at least two additional behavior:
- GROUP type widgets are not reported by the deprecated Timeboard API but are reported by the Dashboard API; I would expect GROUP type widgets to be supported by this provider
- Only Legacy IDs can be used for terraform import, even though these are hard to find in the UI.

### Actual Behavior
At least as a user, it appears that the terraform-provider-datadog maps to the old API.

**Comment by bkabrda** [comment]
This was added in #249 and will be part of next release (hopefully before end of this week).
