### ISSUE TITLE
Provide data source for Datadog IP ranges

### ISSUE THREAD

**Issue by julianvmodesto** [terraform-providers/terraform-provider-datadog#216]
Datadog provides the metadata endpoint https://ip-ranges.datadoghq.com/ for IP addresses.

We can create a data source for this like for the GitHub or AWS Providers:

https://www.terraform.io/docs/providers/github/d/ip_ranges.html
https://www.terraform.io/docs/providers/aws/d/ip_ranges.html

**Comment by bkabrda** [comment]
Implemented in #298, will be part of the next release. Closing this issue.
