### ISSUE TITLE
Document conditional_format in datadog_timeboard

### ISSUE THREAD

**Issue by 2rs2ts** [terraform-providers/terraform-provider-datadog#22]
This feature is not documented so I had thought it wasn't supported.

#### original post

There's not much to this request. Please support this feature.

<img width="671" alt="blue_kubernetes_cluster_health___datadog" src="https://user-images.githubusercontent.com/578891/30669709-255db5cc-9e14-11e7-8554-c8e818b1f36f.png">

It looks like this in the JSON definition of the monitor:

     "conditional_formats": [
        {
          "palette": "white_on_red",
          "value": 1,
          "comparator": ">"
        }
      ]

**Comment by nyanshak** [comment]
I think this is already supported:

```
resource "datadog_timeboard" "example_timeboard" {
  title       = "Example Timeboard"
  description = "Example"

  graph {
    title = "Load Top List"
    viz   = "toplist"

    request {
      q = "top(avg:system.load.1{*} by {environment}, 10, 'mean', 'desc')"

      conditional_format {
        palette    = "white_on_red"
        comparator = ">"
        value      = "3"
      }

      conditional_format {
        palette    = "white_on_yellow"
        comparator = ">"
        value      = "2"
      }

      conditional_format {
        palette    = "white_on_green"
        comparator = "<="
        value      = "2"
      }
    }
  }
}
```

Let me know if that's not what you're looking for.

**Comment by 2rs2ts** [comment]
It's not documented so I wasn't aware it was supported. I will rename this issue so that it talks about documentation instead.
