### ISSUE TITLE
Support Synthetics SSL Certificate Monitoring

### ISSUE THREAD

**Issue by dharada1** [terraform-providers/terraform-provider-datadog#229]
https://docs.datadoghq.com/synthetics/api_tests/?tab=ssltest

<img width="854" alt="スクリーンショット 2019-06-10 17 15 26" src="https://user-images.githubusercontent.com/6387224/59181946-7297ec80-8ba3-11e9-827f-801a51935b52.png">

**Comment by chussenot** [comment]
The API return a response with a `subtype` for the `type='api'`
the `subtype` can be:

* http
* ssl 

Browser test have no subtypes.

**Comment by nmuesch** [comment]
Hey @dharada1, thanks for the feature request. We just released version 2.2.0 of the Datadog Terraform Provider - In addition to some general new features and improvements, this release also includes the addition of Synthetics test SSL support (full changelog here - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/CHANGELOG.md#220-august-19-2019)

Here is an example of what a configuration would look like for this feature - https://www.terraform.io/docs/providers/datadog/r/synthetics.html#example-usage-synthetics-ssl-test-

Given this release, I'll go ahead and close this issue for now, but do let us know if you hit any issues here.
