### ISSUE TITLE
Support check status widget in datadog_timeboard

### ISSUE THREAD

**Issue by 2rs2ts** [terraform-providers/terraform-provider-datadog#23]
I couldn't find API documentation for this widget, so this may be tricky, but it would be great to see support for it.

<img width="100" alt="blue_kubernetes_cluster_health___datadog" src="https://user-images.githubusercontent.com/578891/30671327-31d9eecc-9e1b-11e7-9d4a-8ae773c080b5.png">

**Comment by nyanshak** [comment]
Correct me if I'm wrong, but I don't think that that widget actually exists for timeboards, but only for screenboards. Right now there is no datadog_screenboard terraform resource unfortunately.

Timeboard widgets:

- Timeseries
- Query Value
- Heat Map
- Distribution
- Top List
- Change
- Hostmap

Screenboard widgets:

- Free Text
- Graph
- Query Value
- Toplist
- Change
- Event Timeline
- Event Stream
- Image
- Note
- Alert Graph
- Alert Value
- IFrame
- Check Status
- Service Summary
- Hostmap
- Monitor Summary

**Comment by 2rs2ts** [comment]
I was aware that the two things were different entities but didn't realize that what I thought was a timeboard was a screenboard. Ok, I will close this, and we can hope for a screenboard resource later.
