### ISSUE TITLE
Release v1.10.0

### ISSUE THREAD

**Issue by milanvdm** [terraform-providers/terraform-provider-datadog#235]
It has been a while since a new release of the Datadog provider.

Quite some new features have been added which we really would like to use and since there is no easy way to build the master branch ourselves, we have been waiting for a new release for quite some time now.

**Comment by bkabrda** [comment]
Yeah, we're actually working towards that right now. We discovered several issues while running acceptance tests and so I submitted a PR to get that fixed - #234. Once that's merged, we'll do some more testing and if everything looks fine, we'll do a release. I'll leave this issue open until then.

**Comment by nmuesch** [comment]
Hey @milanvdm version 2.0.0 has just been released! I'll go ahead and close this issue out, thanks for the report.
