### ISSUE TITLE
Feature Request: Downtime by Monitor

### ISSUE THREAD

**Issue by philax** [terraform-providers/terraform-provider-datadog#25]
According to the docs for the Datadog API [downtime](https://docs.datadoghq.com/api/#downtimes), you can provide a monitor_id in order to silence only a specific monitor, or monitor+scope.  This would be extremely helpful in silencing monitors that are like little yippy dogs overnight without having to silence any other monitors for a specific host, instance, tag, container, etc.

**Comment by nyanshak** [comment]
Mute a single monitor forever:
```hcl
resource "datadog_monitor" "foo" {
    ...
   silenced {
      '*' = 0
   }
}
```

Mute by scope (such as by host or role):
```hcl
resource "datadog_monitor" "foo" {
    ...
   silenced {
      'host:i-1234' = 0
   }
}

resource "datadog_monitor" "foo" {
    ...
   silenced {
      'role:db' = 0
   }
}
```

I believe this is already supported. Docs for silencing via the provider: [docs](https://www.terraform.io/docs/providers/datadog/r/monitor.html#silenced). Let me know if I didn't understand the comment and that's not what you're talking about.

@philax

**Comment by MattHodge** [comment]
Looks like what this will do: https://github.com/terraform-providers/terraform-provider-datadog/pull/18

To explain the reason why you would want this:

* You have a single DataDog host that is running a PHP application for an online store.
  * The host is tagged as `host:web_host` and `environment:production`.
  * The host is sending two custom metrics from inside the PHP application:
    * `online_checkout.products_purchased` - increments every time a product is purchased
    * `online_checkout.checkout_errors` - incruments every time there is a failure when someone tries checking out.

You create a monitor for each case:
* Monitor 1 - **A product has been purchased in the last 10 minutes**
* Monitor 2 - **Number of checkout errors < 1**

Your online store doesn't have anyone buying from around 1am-8am each morning, so you want a downtime on this one.

You never want a downtime on checkout errors though, you want to get noticed of this at all hours of the night if someone cannot checkout. 

The way the resource is currently designed, you can only set downtimes on host tags, so you cannot just set `Monitor 1` with a downtime. 

If we can set downtimes by `monitor_id` this scenario is possible using.

Hopefully this explains why its needed :D

**Comment by kikitux** [comment]
As #18 got merged, can we close this?

@philax ?

**Comment by tombuildsstuff** [comment]
Closing @kikitux's request
