### ISSUE TITLE
Follow redirects in resource "datadog_synthetics_test" not working

### ISSUE THREAD

**Issue by hirenshah005** [terraform-providers/terraform-provider-datadog#255]
Hi there,

### Terraform Version
Run `terraform -v` to show the version. 0.12.3

### Affected Resource(s)
Please list the resources as a list, for example:
resource "datadog_synthetics_test"
 ``` 
options = {
    tick_every           = 60
    follow_redirects     = "true"
    min_failure_duration = 300
    min_location_failed  = 2
  }
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/13587968/60530256-fca42280-9d15-11e9-95f3-0d3813583e3c.png)

The "Follow Redirect" should have been enabled.

**Comment by nmuesch** [comment]
Hey @hirenshah005 Thanks for the issue report. We just released the Datadog Provider 2.2.0, which includes a fix for this issue - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/CHANGELOG.md#220-august-19-2019 (And some new features around synthetics)

Given that I'll go ahead and close this issue, but please do let us know if you continue to experience an issue with this on the new version!
