### ISSUE TITLE
Runtime error in 2.1.0 when creating a GraphQL-specific synthetics test

### ISSUE THREAD

**Issue by rafaelmagu** [terraform-providers/terraform-provider-datadog#280]
We have created a few Synthetics tests before but Terraform is crashing when we attempt to create a new one with more assertions.

### Terraform Version
```
Terraform v0.11.13
+ provider.aws v2.22.0
+ provider.datadog v2.1.0
+ provider.pagerduty v1.3.1
+ provider.pingdom v2019.04.17
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `datadog_synthetics_test`

### Terraform Configuration Files
```hcl
resource "datadog_synthetics_test" "production-graphql" {
  type = "api"

  request = {
    method = "POST"
    url    = "https://${var.production_app_url}/"
    body   = "{\"query\":\"{\\n  facilities {\\n    id\\n    name\\n  }\\n}\\n\"}"
  }

  assertions = [
    {
      type     = "statusCode"
      operator = "is"
      target   = "200"
    },
    {
      type      = "body"
      operation = "contains"
      target    = "{\"id\":\"random-uuid-here\""
    },
  ]

  locations = [
    "aws:eu-central-1",
    "aws:us-east-2",
    "aws:ca-central-1",
  ]

  options = {
    min_location_failed = 2
    tick_every          = 60
  }

  name    = "Production - Demo GraphQL"
  message = "@slack-Main_Account-incident-response"
  tags    = ["environment:production", "service:api"]

  status = "live"
}
```

### Panic Output
https://gist.github.com/rafaelmagu/a29d1762c3281703a2fcb040840b2de1

### Expected Behavior
Terraform creates a new Synthetics test with specific assertions for a GraphQL API endpoint.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

### Important Factoids
Fails both on Ubuntu Linux and macOS.

**Comment by nmuesch** [comment]
Hey @rafaelmagu thanks for the issue report. I believe the issue is with the second `assertion` in your config. `operation` should be `operator`, like the first `assertion` definition. Could you try that change and let me know if you still hit an issue?

**Comment by rafaelmagu** [comment]
I will do and report back, but in the meantime, why does it work for planning? (No errors occur and the plan shows accordingly)

—
Sent on the go
Rafael Fonseca

**Comment by nmuesch** [comment]
Currently there isn't a dedicated schema for the `assertions` field and is just a map where any key can be placed - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_synthetics_test_.go#L38 Due to this, there isn't an error on the plan since any key is allowed.

**Comment by nmuesch** [comment]
Hey @rafaelmagu just wanted to see if you had a chance to try out my previous note and if that resolved the issue you were hitting?

**Comment by rafaelmagu** [comment]
@nmuesch apologies for I have forgotten to update this issue. The problem is indeed resolved.
