### ISSUE TITLE
hostmap widget no_group_host and no_metric_host documented but not supported

### ISSUE THREAD

**Issue by 2rs2ts** [terraform-providers/terraform-provider-datadog#284]
### Terraform Version
```
Terraform v0.11.8
+ provider.datadog v2.1.0
+ provider.pagerduty v1.3.1

Your version of Terraform is out of date! The latest version
is 0.12.6. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
- `datadog_dashboard`

### Terraform Configuration Files
From my larger dashboard definition:
```hcl
widget {
  hostmap_definition {
    title          = "Container map (fill by CPU %)"
    node_type      = "container"
    scope          = ["$environment", "$datacenter", "$pod_name", "app:myapp"]
    group          = ["environment", "datacenter"]
    no_group_host  = true
    no_metric_host = true

    request {
      fill {
        q = "avg:process.stat.container.cpu.total_pct{$environment,$datacenter,$pod_name,app:myapp} by {host}"
      }
    }
  }
}

```

### Expected Behavior
This should have worked. The docs have these options listed. I did a quick code search in github and only saw them mentioned in the docs though, not anywhere in the actual code.

### Actual Behavior
```
Error: module.timeboards.datadog_dashboard.coredns: widget.13.hostmap_definition.0: invalid or unknown key: no_group_host



Error: module.timeboards.datadog_dashboard.coredns: widget.13.hostmap_definition.0: invalid or unknown key: no_metric_host
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bkabrda** [comment]
AFAICS you have a typo in your config, you need to use plurals - `no_group_hosts` and `no_metric_hosts` (both with an "s" at the end) - can you try this? (The documentation lists these correctly in plurals.)

**Comment by nmuesch** [comment]
Hey @2rs2ts thanks for the issue report. As @bkabrda mentioned, these should indeed be pluralized. The example configuration in the documentation was correct, but it looks like the descriptions for these fields had them as singular. I've opened a PR to fix the documentation. Can you give that a try and let us know if you continue to hit any issues with this? (Doc PR - https://github.com/terraform-providers/terraform-provider-datadog/pull/285)

**Comment by 2rs2ts** [comment]
@nmuesch thanks, the plurals work. And thank you for updating the docs.
