### ISSUE TITLE
404 error finding datadog_integration_pagerduty_service_object

### ISSUE THREAD

**Issue by ryanisnan** [terraform-providers/terraform-provider-datadog#299]
Hello,

I am encountering an issue with the datadog pagerduty integration, specifically, the `datadog_integration_pagerduty_service_object` resource.

Initial creation of the resource works via `terraform plan` / `apply`.

Subsequent updates fail with:

```
Error: Error refreshing state: 1 error occurred:
	* module.main_monolith_dd_monitors.datadog_integration_pagerduty_service_object.datadog_pd_integration: 1 error occurred:
	* module.main_monolith_dd_monitors.datadog_integration_pagerduty_service_object.datadog_pd_integration: datadog_integration_pagerduty_service_object.datadog_pd_integration: API error 404 Not Found: {"errors": ["Service not found"]}
```
The configuration for the resource is:

```
resource "datadog_integration_pagerduty_service_object" "datadog_pd_integration" {
  depends_on   = ["datadog_integration_pagerduty.pd"]
  service_name = "${var.pd_service_name}"
  service_key  = "${var.pd_service_key}"
}
```

The variable `pd_service_name` or `pd_service_key` do not change between the initial creation and subsequent updates.

An odd workaround I've found is to remove the `datadog_integration_pagerduty_service_object` from state manually, and re-plan/applying.

### Terraform Version
➜  production git:(master) ✗ terraform -v
Terraform v0.11.14
+ provider.aws v1.60.0
+ provider.datadog v2.2.0
+ provider.grafana v1.5.0
+ provider.pagerduty v1.3.1
+ provider.random v2.2.0
+ provider.sentry (unversioned)
+ provider.template v2.1.2

### Affected Resource(s)
- `datadog_integration_pagerduty_service_object`

### Expected Behavior
I would expect my module to be updated.

### Actual Behavior
The module does not get updated, as the `datadog_integration_pagerduty_service_object` is not found.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
There are two modules at play here. 1 module creates the `pagerduty_service` and the `pagerduty_service_integration` to datadog.

The other module is the one that implements the `datadog_integration_pagerduty_service_object` as well as several monitors. The second module is where the failure is occurring.

**Comment by hiscal2015** [comment]
I have the same issue

**Comment by bkabrda** [comment]
Hey @ryanisnan thanks for the report. Did you add `individual_services = true` to the `datadog_integration_pagerduty` resource as documented in [1]? If so, could you also post what terraform shows as plan on the `terraform apply` run that makes this fail?

[1] https://www.terraform.io/docs/providers/datadog/r/integration_pagerduty.html#example-usage

**Comment by bkabrda** [comment]
Thanks for the additional information @alekhrycaiko, I have reproduced the error and I think I know where the issue is. I'll try to push a fix today.
