### ISSUE TITLE
Support cancelled downtime gracefully

### ISSUE THREAD

**Issue by iksaif** [terraform-providers/terraform-provider-datadog#315]
When a downtime managed by terraform is cancelled via the web UI, we get the following: `API error 400 Bad Request: {"errors":["cannot update a canceled downtime"]}`

@bkabrda suggests that we switch to the following behavior: when the downtime is canceled, we should consider it deleted in our provider, which would automatically make TF suggest recreating it. so when reading it, we have to look at “canceled” and if that’s true, we have to pretend like it doesn’t exist - that should make TF behave correctly and suggest recreating it. 

This sounds good from our side

**Comment by octplane** [comment]
Also, on our production endpoint, it's possible to re-enable a disabled downtime:

```
cloudops-cli terraform plan -parallelism=50 -out=.terraform.plan | landscape
~ datadog_downtime.working-hours-only-weekdays
    disabled:   "true" => "false"

Plan: 0 to add, 1 to change, 0 to destroy.

Really apply this changes? Enter "y" to continue. Anything else will exit. y
cloudops-cli terraform apply -parallelism=50 .terraform.plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
datadog_downtime.working-hours-only-weekdays: Modifying... (ID: 626473591)
  disabled: "true" => "false"
datadog_downtime.working-hours-only-weekdays: Modifications complete after 1s (ID: 626473591)
```

But this does nothing to the modified downtime (it's still not available in the UI).

On other platforms (ie `staging`), the message reported by @iksaif  is the one we get.

Another annoying thing is the multiple words used: `cancel` (doc), `disable` (tf field) and the little trashcan that's visible in the UI.
