### ISSUE TITLE
Optional variables for apm_query cause crash or error when excluded 

### ISSUE THREAD

**Issue by entscheidungsproblem** [terraform-providers/terraform-provider-datadog#316]
Hi there,

### Terraform Version
Terraform v0.12.1
+ provider.datadog v2.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_dashboard

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "application_overview" {
  title        = "APM Test"
  is_read_only = false
  layout_type  = "ordered"

  widget {
    group_definition {
      layout_type = "ordered"
      title       = "Duration"

      widget {
        timeseries_definition {
          title = "Duration timeseries"
          request {
            apm_query {
              index = "trace-search"
              compute = {
                aggregation = "avg"
                facet       = "@duration"
                interval    = "auto"    #a) Comment out
              }
              search = {
                query = "status:ok"
              }
              group_by {    #d) Comment out
                facet = "resource_name"    #c) Comment out
                limit = 5
                sort = {
                  facet       = "@duration"    #b) Comment out
                  aggregation = "avg"
                  order       = "desc"
                }
              }
            }
            display_type = "line"
          }
        }
      }
    }
  }
}

```

### Debug Output
a)  `timeseries_definition:request:apm_query:compute:interval` excluded
[debug](https://gist.github.com/entscheidungsproblem/feeb993cd8c307c6423e50d931ea5a4a)
[crash](https://gist.github.com/entscheidungsproblem/5f2708f9dfe8a97d15e2fa223e7ab62d)
b) `timeseries_definition:request:apm_query:group_by:sort:facet` excluded
[debug](https://gist.github.com/entscheidungsproblem/80e3170ecf3cfce6293eaadc22a8058b)
[crash](https://gist.github.com/entscheidungsproblem/6c297f7b9471be7871bc0bc29f21369b)
c) `timeseries_definition:request:apm_query:group_by:facet` excluded
[debug](https://gist.github.com/entscheidungsproblem/4b1defec27e417b451d10ca761b7722c)
d) `timeseries_definition:request:apm_query:group_by` excluded
[debug](https://gist.github.com/entscheidungsproblem/c15e1ba85319e851eda97fce6966544c)

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
a)  `timeseries_definition:request:apm_query:compute:interval` excluded
[crash](https://gist.github.com/entscheidungsproblem/5f2708f9dfe8a97d15e2fa223e7ab62d)
b) `timeseries_definition:request:apm_query:group_by:sort:facet` excluded
[crash](https://gist.github.com/entscheidungsproblem/6c297f7b9471be7871bc0bc29f21369b)

### Expected Behavior
Create dashboard with a `timeseries_definition` with `apm_query` using the arguments as directed in the [wiki](https://www.terraform.io/docs/providers/datadog/r/dashboard.html), specifically working correctly when excluding optional arguments. Comments in the code above shows what lines are excluded for each case.
a) This case excludes `timeseries_definition:request:apm_query:compute:interval`
b) This case excludes `timeseries_definition:request:apm_query:group_by:sort:facet`
c) This case excludes `timeseries_definition:request:apm_query:group_by:facet`
d) This case excludes `timeseries_definition:request:apm_query:group_by`

### Actual Behavior
a) Terraform crashes when `timeseries_definition:request:apm_query:compute:interval` is not set.
b) Terraform crashes when `timeseries_definition:request:apm_query:group_by:sort:facet` is not set.
c) Terraform errors when `timeseries_definition:request:apm_query:group_by:facet` is not set.
d) No data is shown on the Datadog dashboard when `group_by` is not set.
This is the json of the widget (for d)):
```json
{
  "viz": "timeseries",
  "requests": [
    {
      "apm_query": {
        "index": "trace-search",
        "search": {
          "query": "status:ok"
        },
        "compute": {
          "facet": "@duration",
          "aggregation": "avg"
        }
      },
      "type": "line",
      "conditional_formats": [],
      "aggregator": "avg"
    }
  ],
  "autoscale": true
}
```
It works when changed to:
```json
{
  "viz": "timeseries",
  "requests": [
    {
      "apm_query": {
        "index": "trace-search",
        "search": {
          "query": "status:ok"
        },
        "groupBy":[],    #This line is needed
        "compute": {
          "facet": "@duration",
          "aggregation": "avg"
        }
      },
      "type": "line",
      "conditional_formats": [],
      "aggregator": "avg"
    }
  ],
  "autoscale": true
}
```
### Steps to Reproduce
0. a) Remove `timeseries_definition:request:apm_query:compute:interval`
0. b) Remove `timeseries_definition:request:apm_query:group_by:sort:facet`
0. c) Remove `timeseries_definition:request:apm_query:group_by:facet`
0. d) Remove `timeseries_definition:request:apm_query:group_by`
1. `terraform apply`

**Comment by bkabrda** [comment]
Hey, thanks for the report! I fixed a) in #322 and b) and c) is waiting for review in #325. For d), we'll need some insight into the web app itself, so tagging @enbashi here to get help.

**Comment by entscheidungsproblem** [comment]
Thanks for your help! Let me know if I can provide any other info.

**Comment by bkabrda** [comment]
Ping @enbashi could you take a look at the issue d) from the original report and see if there's something we can do about that? Thanks!

**Comment by enbashi** [comment]
> Ping @enbashi could you take a look at the issue d) from the original report and see if there's something we can do about that? Thanks!

Sure, I will take a look. Apologies for the delay, I missed the previous ping.

**Comment by jbenais** [comment]
Apologies also for the delay, the issue d) was fixed few weeks ago. The `group_by` attribute should now be fully optional and can be omitted in the terraform configuration. Please let us know if you see any other issue! Thanks a lot for your patience

**Comment by bkabrda** [comment]
So it looks like all 4 problems from the original issue report are now fixed. I'm going to close this. @entscheidungsproblem feel free to open a new issue if you have more problems. Thanks everyone involved!
