### ISSUE TITLE
Add AWS Log Lambda Integration

### ISSUE THREAD

**Issue by taiidani** [terraform-providers/terraform-provider-datadog#318]
Feature request for adding to the existing Datadog-AWS integration with support for the "Collect Logs" portion.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/902500/65051266-acecf480-d91d-11e9-8a44-ad019962670b.png">

It appears as though [Datadog has added API support](https://docs.datadoghq.com/api/?lang=python#add-aws-log-lambda-arn) for setting up these integrations, although I don't think the provider's upstream client library has updated to match yet.

**Comment by taiidani** [comment]
The functionality appears to have been added to this provider's client library: https://github.com/zorkian/go-datadog-api/releases/tag/v2.25.0

**Comment by mhaley-miovision** [comment]
This looks pretty straight forward to add.  I am going to start work on this today. My thoughts are to add two new resources.  One to manage lambda arns attached to AWS accounts and the other to manage which logging services are enabled for AWS accounts.

**Comment by gzussa** [comment]
This should be solved now. Feel free to upgrade to our latest version and try it out.
