### ISSUE TITLE
502 Bad Gateway for datadog_service_level_objective

### ISSUE THREAD

**Issue by ScOut3R** [terraform-providers/terraform-provider-datadog#319]
Hi,

The datadog_service_level_objective resource cannot create the associated resource, because the Datadog API returns a 502 Bad Gateway error. This has been consistent for the last 24 hours while other parts of the API (monitors, dashboards) work perfectly.

### Terraform Version
Terraform v0.12.8
+ provider.aws v2.28.1
+ provider.datadog v2.4.0

### Affected Resource(s)
- datadog_service_level_objective

### Terraform Configuration Files
```hcl
resource "datadog_service_level_objective" "playmaker" {
  name = "Playmaker"
  type = "metric"
  tags = local.tags

  query {
    numerator   = "min(last_1h):min:aws.route53.health_check_status{aws_account:${local.aws_account},name:playmaker}} < 1"
    denominator = "min(last_1h):min:aws.route53.health_check_status{aws_account:${local.aws_account},name:playmaker}"
  }

  thresholds {
    timeframe = "30d"
    target    = 99.9
    warning   = 99.95
  }
}
```

### Debug Output
https://gist.github.com/ScOut3R/d75dde5e83926fe1e64b1e74c3f18bc4

### Expected Behavior
SLO gets created

### Actual Behavior
API 502 Bad Gateway error prevents the resource from being created.

### Steps to Reproduce
1. `terraform apply`

**Comment by nmuesch** [comment]
Hey @ScOut3R apologies for the delay here. I unfortunately wasn't able to reproduce the issue you reported. Are you still experiencing these 502, and is it consistent on each apply? If so, could you provide the full terraform apply output in debug mode (exluding any sensitive information like API/APP keys)

**Comment by ScOut3R** [comment]
Hi @nmuesch, thank you for the follow-up. I tried it now and it works. Much appreciated! :)
