### ISSUE TITLE
Disable feature for datadog provider 

### ISSUE THREAD

**Issue by anosulchik** [terraform-providers/terraform-provider-datadog#32]
Hi there,

Our terraform configuration that contains bunch of AWS resources also includes datadog resources (monitors and dashboards). Terraform datadog provider works just fine, i.e. we can create, delete or delete datadog resources without any issues. At the same time in case Datadog service is `down`, we're not able to apply any changes into our AWS resources which are defined in the same config as datadog resources. In this case terraform just fails on initialization of datadog provider.

This is very important for us to be able to deploy changes into our AWS resources even if Datadog is down or suffers from partial degradation.

We're using S3 terraform remote backend, so if I comment out all datadog resources and datadog provider in terraform, terraform init and plan/apply will be still failing trying to init datadog provider (it fails on missing DD keys).

What do you guys think about disable feature datadog provider? E.g. if DD provider is disabled, terraform will ignore all DD resources during plan/apply.

Looking forward to receiving reply from you.

Thank you!

**Comment by skyzyx** [comment]
Quite honestly, it sounds like you're coupling dependencies that ought not be coupled. I would vote 👎 for this feature request because I believe it reinforces bad behaviors.

**Comment by nmuesch** [comment]
Hey @anosulchik Thanks for raising this. If I understand properly, we'll need https://github.com/hashicorp/terraform/issues/14132 to properly resolve this issue? 

From reading through some Terraform docs, do you think something like Resource Targeting would help address the issue here - https://www.terraform.io/docs/commands/plan.html#resource-targeting ? I.e. in the case of an issue on the Datadog side, just providing the path to your AWS/PagerDuty modules?

**Comment by anosulchik** [comment]
Hey @nmuesch, yeah -- hashicorp/terraform#14132 would solve our problem. For example, we created some resources in AWS (using aws provider) and datadog (using datadog terraform provider that works with datadog api) and need to update aws resources when datadog api is down. Currently it's not possible since whole terraform plan/apply will fail regardless if `-target` is provided or not.

**Comment by nmuesch** [comment]
Thanks for the information! I don't think this is something that we'll tackle on the Datadog Provider side, but could help review any PRs if someone wanted to take a crack at it. Going to close this one in the meantime.
