### ISSUE TITLE
datadog slo always add \n\n to description

### ISSUE THREAD

**Issue by iksaif** [terraform-providers/terraform-provider-datadog#334]
We use the new datadog_service_level_objective and it works great but it always add a `\n\n` at the end of the description which means that the plan will always display a change even if there is none :)

**Comment by nmuesch** [comment]
Hey, thanks for the issue report. The SLO resource has some logic around explicitly trimming whitespace - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_service_level_objective.go#L33. Additionally I wasn't able to reproduce this issue on TF version 0.11.10 or 0.12.7

Could you share the config you're able to reproduce this with as well as the plan you see between runs where the diff should be empty?

**Comment by nmuesch** [comment]
Discussed offline a bit. The following config reproduces this behavior:

```
resource "datadog_service_level_objective" "foo" {
  name               = "Example Metric SLO via TF"
  type               = "metric"
  description        = <<EOT
First line.
Second line.
Third line
EOT
  query {
    numerator = "sum:my.custom.count.metric{type:good_events}.as_count()"
    denominator = "sum:my.custom.count.metric{*}.as_count()"
  }

  thresholds {
    timeframe = "7d"
    target = 99.9
    warning = 99.99
    target_display = "99.900"
    warning_display = "99.990"
  }

  thresholds {
    timeframe = "30d"
    target = 99.9
    warning = 99.99
    target_display = "99.900"
    warning_display = "99.990"
  }

  tags = ["foo:bar", "baz"]
}
```
This appears to leave the `\n\n` on the end in the config despite the schema attempting to trim this. 
One short term solution is to wrap the description string in the TF `trimspace` helper - https://www.terraform.io/docs/configuration/functions/trimspace.html
