### ISSUE TITLE
error rpc, code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by adoux** [terraform-providers/terraform-provider-datadog#336]
Hi,

We are experiencing issues with v2.4 of datadog module when trying to create dashboards, it fails on some elements when running `terraform apply` but doing one by one works.
Also, it works great with Datadog module v2.2.

Thanks in advance for your help !

### Terraform Version

Terraform v0.12.9
+ provider.datadog v2.4.0

### Affected Resource(s)

datadog_dashboard (at least)

### Terraform Configuration Files

```
terraform {
  backend "s3" {}
}

locals {
  tfdefaultsettingsfile = "./tfsettings.yaml"
  tfdefaultsettingsfilecontent = fileexists(local.tfdefaultsettingsfile) ? file(local.tfdefaultsettingsfile) : "NoTFdefaultSettingsFileFound: true"
  default_tfsettings   = yamldecode(local.tfdefaultsettingsfilecontent)

  tfsettingsfile        = "./environments/${terraform.workspace}/tfsettings.yaml"
  tfsettingsfilecontent = fileexists(local.tfsettingsfile) ? file(local.tfsettingsfile) : "NoTFSettingsFileFound: true"
  tfworkspacesettings   = yamldecode(local.tfsettingsfilecontent)

  tfsettings            = merge(local.default_tfsettings, local.tfworkspacesettings)
  
}

provider "datadog" {
  version = "~> 2.2"
  api_key = "${local.tfsettings.dd_api_key}"
  app_key = "${local.tfsettings.dd_app_key}"
}

module "datadog" {
  source              = "./modules/datadog"
  jahia_user_accounts = local.tfsettings.jahia_user_accounts
  jahia_ro_user_accounts = local.tfsettings.jahia_ro_user_accounts
  synthetics_envs     = local.tfsettings.synthetics
}
```

### Debug Output

https://gist.github.com/adoux/37d4ee73cf1a6d0e532f9b66a5cc467b

### Panic Output

on a previous run :

https://gist.github.com/adoux/37d4ee73cf1a6d0e532f9b66a5cc467b#file-crash-log

### Expected Behavior

Dashboard should have been created

### Actual Behavior

Crash

### Steps to Reproduce

`terraform apply`

### Important Factoids

- It is fully functionnal with datadog module v2.2, issue begins with v2.3 and is still there with 2.4
- Running `terraform apply -target=<specific_dashboard>` works even if it failed on the same dashboard during global `terraform apply`

### References

No reference

**Comment by nmuesch** [comment]
Hey @adoux thanks for the issue report, apologies for the trouble here. It looks like you're hitting the issue that was recently fixed with the following PRs:

https://github.com/terraform-providers/terraform-provider-datadog/pull/322
https://github.com/terraform-providers/terraform-provider-datadog/pull/325

These should be released with the next version of the provider. In the meantime, with version 2.4, its required that the interval and facet sections be explicitly set with dashboards that have an APM or Log Query section

**Comment by adoux** [comment]
Hi Nicolas,

Ok I understand, I'll wait for the next version then.

Thank you for our help !

Axel
