### ISSUE TITLE
monitor summary widget support

### ISSUE THREAD

**Issue by generalpiston** [terraform-providers/terraform-provider-datadog#340]
Feature request: [Monitory Summary Widget](https://docs.datadoghq.com/graphing/widgets/monitor_summary/)

### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.12.0
+ provider.datadog v2.3.0
```

### Affected Resource(s)

- datadog_dashboard

**Comment by nmuesch** [comment]
Hey @generalpiston thanks for the issue report. The `dashboard` resource currently has support for the manage_status` widget type. Is this what you're looking for? More information as well as an example config can be found here - https://www.terraform.io/docs/providers/datadog/r/dashboard.html#manage_status_definition

**Comment by generalpiston** [comment]
@nmuesch that did the trick. Any chance we can add documentation about it being the `Monitor Summary Widget`?

**Comment by nmuesch** [comment]
Just merged the above PR. I'll go ahead and close this issue for now, thanks again for bringing this up.

**Comment by generalpiston** [comment]
Thanks @nmuesch !
