### ISSUE TITLE
panic with optional argument missing

### ISSUE THREAD

**Issue by wguto** [terraform-providers/terraform-provider-datadog#345]
### Terraform Version
0.12.12

### Affected Resource(s)
- datadog_dashboard

### Panic Output
https://gist.github.com/wguto/299962523cf05f48727457756412703f

### Actual Behavior
What actually happened?
Crashes horribly with missing optional vars

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Just apply this gist.
https://gist.github.com/wguto/ff6b94c353413539c5e51483c1071283

So, if you do not pass the argument "interval" ( line 21 ) and "facet" line 32, It breaks horribly, although, in the documentation, it says it is optional. However, even if it is mandatory and you not pass it, it should not panic.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
- NO

**Comment by bkabrda** [comment]
I think this was solved in 2.5.0 release (see first bullet point in the "BUGFIXES" section in [1]). Could you try this with 2.5.0 and let us know if that fixes your problem?

[1] https://github.com/terraform-providers/terraform-provider-datadog/blob/master/CHANGELOG.md#250-october-22-2019

**Comment by wguto** [comment]
Thank you @bkabrda , it worked with the version 2.5.0.
