### ISSUE TITLE
GeoIP parser for datadog_logs_custom_pipeline

### ISSUE THREAD

**Issue by crolfe** [terraform-providers/terraform-provider-datadog#348]
I am currently trying to Terraform an existing Datadog logging pipeline that uses the [GeoIP parser](https://docs.datadoghq.com/logs/processing/processors/?tab=ui#geoip-parser).  I tried looking in the provider docs, code, and issues, but couldn't seem to find any reference to this parser.  

Am I missing something obvious, or is this parser missing from this resource?  If it is indeed missing, would it be possible to add it?

**Comment by bkabrda** [comment]
Hey 👋 we have an example and basic documentation for `geo-ip-parser` in the documentation for custom logs pipelines: https://www.terraform.io/docs/providers/datadog/r/logs_custom_pipeline.html - please let me know if you find that sufficient or if something needs updating. Thanks.

**Comment by gzussa** [comment]
Closing this issue. Feel free to reopen if needed. Thanks
