### ISSUE TITLE
Feature Request: datadog_dashbbaord resouce public_url option

### ISSUE THREAD

**Issue by mlindes** [terraform-providers/terraform-provider-datadog#349]
The `datadog_dashboard` resource should allow the option to generate a public_url.
If `layout_type="free"` (Screenboards), the resource should be able to trigger the creation of a public url & have that url as an output option.

**Comment by nmuesch** [comment]
Hey @mlindes Thanks for the feature request. Currently this isn't available via the API and would need to be added there first. I've logged the request to the appropriate team but I unfortunately don't have a timeline on when/if this will be tackled. Thanks !
