### ISSUE TITLE
yaxis not working with timeseries_definition widget

### ISSUE THREAD

**Issue by generalpiston** [terraform-providers/terraform-provider-datadog#353]
### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.12.0
+ provider.datadog v2.3.0
```

### Affected Resource(s)
datadog_dashboard.timeseries_definition

### Terraform Configuration Files
```hcl
widget {
    timeseries_definition {
      request {
        q = "100 * max:system.disk.in_use{env:<>} by {host}"
        display_type = "bars"
        style {
          palette = "cool"
          line_type = "solid"
          line_width = "normal"
        }
      }
      yaxis {
        scale = "log"
        max = 100
        include_zero = true
      }
      show_legend = true
      time = {
        live_span = "1h"
      }
    }
    layout = {
      height = 22
      width = 50
      x = 15
      y = 0
    }
  }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior

It should go through.

### Actual Behavior

It failed with the error `Error: ...: widget.0.timeseries_definition.0: invalid or unknown key: yaxis`.

### Steps to Reproduce

1. Create a terraform definition with the `datadog_dashboard` defined above.
2. `terraform init` && `terraform apply`.

### References

- https://www.terraform.io/docs/providers/datadog/r/dashboard.html#timeseries_definition
- https://www.terraform.io/docs/providers/datadog/r/dashboard.html#yaxis-2

**Comment by nmuesch** [comment]
Hey @generalpiston `yaxis` and `event` support were added to the provider in version 2.4.0 - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/CHANGELOG.md#240-september-11-2019 Would you be able to upgrade to the latest version of the provider and let us know if you continue to hit an issue?

**Comment by generalpiston** [comment]
@nmuesch that in fact hit the issue. Thank you for pointing it out.

**Comment by generalpiston** [comment]
It looks like `include_zero` isn't being respected. @nmuesch  can you confirm?

**Comment by nmuesch** [comment]
Hey @generalpiston Yeah I've confirmed internally that `include_zero`, isn't compatible with the `log` scale. This is blocked by design as it'd mean having to graph an infinite number, log(0) . 🙂 

This should work for other scale types though ! Let me know if you hit an issue with any others.

**Comment by generalpiston** [comment]
@nmuesch figured :-p. Thank you!

**Comment by nmuesch** [comment]
No problem ! Glad things are working for you. I've passed along your feedback
