### ISSUE TITLE
Building a dashboard with a query_value_definition doesn't work when the request uses log_query but has no group_by

### ISSUE THREAD

**Issue by reidlevesque** [terraform-providers/terraform-provider-datadog#362]
##
Building a dashboard with a `query_value_definition` doesn't work when the `request` uses `log_query` but has no `group_by`.

### Affected Resource(s)
- datadog_dashboard
  - query_value_definition
    - log_query

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "log_indexing_dashboard_test" {
  title        = "Log Indexing - Testing"
  layout_type  = "ordered"

  widget {
    query_value_definition {
      title = "Total Log Volume"
      request {
        log_query {
          index = "main"
          compute = {
            aggregation = "count"
          }
          search = {
            query = ""
          }
        }
        aggregator = "avg"
      }
    }
  }
}
```

### Actual Behavior
This JSON gets sent to the Datadog API from Terraform. When we go to the UI, the dashboard shows `(no data)`. Editing it in the UI and simply clicking Done fixes the issue.
```JSON
{
  "title": "Log Indexing - Testing",
  "widgets": [
    {
      "definition": {
        "type": "query_value",
        "requests": [
          {
            "aggregator": "avg",
            "log_query": {
              "index": "main",
              "compute": {
                "aggregation": "count"
              },
              "search": {
                "query": ""
              }
            }
          }
        ],
        "title": "Total Log Volume"
      }
    }
  ],
  "layout_type": "ordered",
  "id": "<ID>"
}
```

### Expected Behavior
The JSON being sent is missing a `"group_by": []`. When I send this JSON (same as above with the `"group_by": []` line added) the dashboard works as expected.
```JSON
{
  "title": "Log Indexing - Testing",
  "widgets": [
    {
      "definition": {
        "type": "query_value",
        "requests": [
          {
            "aggregator": "avg",
            "log_query": {
              "index": "main",
              "compute": {
                "aggregation": "count"
              },
              "search": {
                "query": ""
              },
              "group_by": []
            }
          }
        ],
        "title": "Total Log Volume"
      }
    }
  ],
  "layout_type": "ordered",
  "id": "<ID>"
}
```

### Steps to Reproduce
1. `terraform apply`

**Comment by nmuesch** [comment]
Hey @reidlevesque Apologies for the delay here and thanks for raising this issue. There was another recent issue report of this - https://github.com/terraform-providers/terraform-provider-datadog/issues/316#issuecomment-584862846

Additionally I was able to run a test with the helpful configuration you provided and can confirm I see data on the created widget. 
I'll go ahead and close this issue for now, but please let me know if you continue to experience this issue and we can open it back up!
