### ISSUE TITLE
Allow to use data source for Datadog IP anonymously (no api key requirement)

### ISSUE THREAD

**Issue by mechastorm** [terraform-providers/terraform-provider-datadog#368]
I am very glad we got #216 resolved through #298. Thanks again to @dabcoder for this.

It would be good though if we could call [`datadog_ip_ranges`](https://www.terraform.io/docs/providers/datadog/d/ip_ranges.html) without an API key (so anonymously).

This is similar to the [Github Provider](https://www.terraform.io/docs/providers/github/index.html) where there is an `anonymous` flag. 

Is there a chance we could do this for the datadog provider?

The reasons why this is useful
- In some terraform states, we sometimes are defining just the firewall rules that also include datadog IPs. This terraform state is usually separate from our Datadog monitors.
- This makes it very hard to having to populate Datadog API keys in remote states do not actually to actually create/manage Datadog resources extensively.

**Comment by nmuesch** [comment]
Hey @mechastorm Thanks for the detailed issue report! I believe this use case should be addressed when this PR is merged - https://github.com/terraform-providers/terraform-provider-datadog/pull/474, which should allow you to not set credentials in your provider config, and skip the api validation step.
