### ISSUE TITLE
An argument named "xxxx" is not expected here

### ISSUE THREAD

**Issue by calebtote** [terraform-providers/terraform-provider-datadog#371]
### Terraform Version
Terraform v0.12.17
+ provider.datadog v2.5.0

### Terraform Configuration Files
```# Configure the Datadog provider
provider "datadog" { 
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key

  version = "2.5.0"
}

module "lb" {
  source = "../modules/lb"

  env = var.env
  evaluation_delay = var.evaluation_delay
  include_tags = var.include_tags
  locked = var.locked
  notify = var.notify
  notify_no_data = var.notify_no_data
  require_full_window = var.require_full_window
}


module "logs" {
  source = "../modules/logs"

  env = var.env
  evaluation_delay = var.evaluation_delay
  include_tags = var.include_tags
  locked = var.locked
  notify = var.notify
  notify_no_data = var.notify_no_data
  require_full_window = var.require_full_window
}

module "rds" {
  source = "../modules/rds"

  env = var.env
  evaluation_delay = var.evaluation_delay
  include_tags = var.include_tags
  locked = var.locked
  notify = var.notify
  notify_no_data = var.notify_no_data
  require_full_window = var.require_full_window
}

module "redis" {
  source = "../modules/redis"

  env = var.env
  evaluation_delay = var.evaluation_delay
  include_tags = var.include_tags
  locked = var.locked
  notify = var.notify
  notify_no_data = var.notify_no_data
  require_full_window = var.require_full_window
}
```

### Debug Output
https://gist.github.com/calebtote/7fd7d24df475d28e9ab52a7257859b23

### Expected Behavior
I should be able to add more modules

### Actual Behavior
This only happens why trying to add a new module to the file (module "logs") - it doesn't matter where I add the module in the file or with which text editor, the errors are always the same. The current file is source controlled and works as expected if I do not attempt to add a new module.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by therve** [comment]
Hello,

Sorry for not responding earlier. It sounds like an issue with the input variables declared in your module? If you module doesn't have the declared variables, `An argument named "foo" is not expected here` is what terraform will output. It's a bit hard to reproduce exactly without the terraform config. Don't hesitate to reopen if you're still having the issue.

Thanks.
