### ISSUE TITLE
API responds with Non-numeric threshold value.

### ISSUE THREAD

**Issue by parabolic** [terraform-providers/terraform-provider-datadog#372]
I am getting an error when trying to use threshold in a datadog monitor.

### Terraform Version
```
Terraform v0.12.18
+ provider.datadog v2.5.0
```

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "default" {
  name               = "Abnormal logs volume for ${module.label.id}"
  type               = "log alert"
  message            = "alert @xxx@xxx.xxx"
  escalation_message = "alert @xxx@xxx.xxx"
  query              = "logs('*').index('main').rollup('count').last('5m') >= 10000"
  enable_logs_sample = true
  notify_no_data     = false
  renotify_interval  = 60

  # Dummy values just to get the thresholds working.
  thresholds = {
    ok       = 1
    warning  = 4
    critical = 5
  }
  notify_audit = false
  timeout_h    = 60
  include_tags = true

  tags = module.label.attributes
}

```

### Debug Output
```
Error: error updating monitor: API error 400 Bad Request: {"errors":["Non-numeric threshold value."]}

  on main.tf line 17, in resource "datadog_monitor" "default":
  17: resource "datadog_monitor" "default" {

```

### Panic Output
None.

### Expected Behavior
A monitor with thresholds is created.

### Actual Behavior
Got an error from the API.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Even though the struct from the golang code uses json to properly structure the map https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_monitor.go#L195-L222 in the plan output I see that the threshold values are stringified:
```hcl
      + thresholds          = {
          + "critical" = "5"
          + "ok"       = "1"
          + "warning"  = "4"
        }
```
Which leads to the above mentioned errors.
### References
None

**Comment by dabcoder** [comment]
Confirmed. Getting the same `400` code in response from the API with a `metric alert`. We'll investigate.

**Comment by dabcoder** [comment]
Correction, I am not getting any `400` in response with a metric alert and the request succeeds. Are you getting a `400` with all monitor types (alert) or only with the `logs alert`?

**Comment by parabolic** [comment]
Hi @dabcoder thanks for helping out.
You are correct I was able to create a monitor with the following values ( listing just the changes here ):
```hcl
type                = "metric alert"

query               = "avg(last_5m):avg:system.cpu.usage{*} >= 30"
thresholds          = {
"critical" = "30"
"ok"       = "10"
"warning"  = "20"
        }

```

**Comment by ianwsperber** [comment]
I see this error when the type is "log alert", so I think thresholds is broken for log alert

**Comment by platinummonkey** [comment]
these must use double quotes, not single quotes. The error message is misleading and I've created an internal ticket, but using double quotes will fix your problem: 

```
"logs(\"*\").index(\"main\").rollup(\"count\").last(\"5m\") >= 10000"
```

**Comment by bkabrda** [comment]
Thanks for the explanation. I'll leave this issue open until this is fixed on the API side.

**Comment by shanab** [comment]
I just bumped into the same issue. Any timeline on when the API can be fixed?
Thanks.

**Comment by therve** [comment]
The error message has been cleared up, as well as the error for threshold management. Closing it for now, thanks.
