### ISSUE TITLE
Any way to use environment variable for private_key field on gcp integration?

### ISSUE THREAD

**Issue by inductor** [terraform-providers/terraform-provider-datadog#377]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

0.12.18

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_integration_gcp

### Terraform Configuration Files
Just like the [example](https://www.terraform.io/docs/providers/datadog/r/integration_gcp.html)
```hcl
# Create a new Datadog - Google Cloud Platform integration
resource "datadog_integration_gcp" "awesome_gcp_project_integration" {
  project_id     = "awesome-project-id"
  private_key_id = "1234567890123456789012345678901234567890"
  private_key    = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
  client_email   = "awesome-service-account@awesome-project-id.iam.gserviceaccount.com"
  client_id      = "123456789012345678901"
  host_filters   = "foo:bar,buzz:lightyear"
}
```

### Expected Behavior
Able to use environment variables for private key, or any other dynamic method to get a value out of the terraform ecosystem.

### Actual Behavior
You have to write it in the tf file.

**Comment by bkabrda** [comment]
Hey 👋 this looks more like a general Terraform question than something related to our provider. IIUC you should be able to use environment variables to get values to Terraform config, please see: https://learn.hashicorp.com/terraform/getting-started/variables.html#from-environment-variables

If that doesn't help, I'd suggest following up with Terraform community to get more help: https://discuss.hashicorp.com/c/terraform-core

Thanks!
