### ISSUE TITLE
Another case of the DD API rewriting a value

### ISSUE THREAD

**Issue by brendanjerwin** [terraform-providers/terraform-provider-datadog#38]
### Terraform Version
0.11.1
DD provider 1.0.2

### Affected Resource(s)
datadog_timeboard

### Debug Output
` graph.0.style.palette_flip:                                          "false" => "0"`

### Expected Behavior
Should not apply a change.

### Actual Behavior
Detected a diff and applied a change. Appears like #3

**Comment by masci** [comment]
Closing as a duplicate of https://github.com/terraform-providers/terraform-provider-datadog/issues/29
