### ISSUE TITLE
cannot unmarshal processor of type: geo-ip-parser

### ISSUE THREAD

**Issue by non7top** [terraform-providers/terraform-provider-datadog#382]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.12.18
+ provider.datadog v2.5.0
```
### Affected Resource(s)
`datadog_logs_custom_pipeline`

### Terraform Configuration Files
```
resource "datadog_logs_custom_pipeline" "test" {
  filter {
        query = "*"
    }
    name = "Parse Attribute "
    is_enabled = false
}
```
Error appears during import of existing pipeline

  `$ terraform import module.pipelines.datadog_logs_custom_pipeline.test XXXXXXXXXXXXXXX`

Apparently geo-ip processor is not supported yet

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**Comment by bkabrda** [comment]
Geo IP parsers are supported since provider version 2.6.0, please give that a go. I'm closing this issue, feel free to open a new one if something doesn't work as expected. Thanks!
