### ISSUE TITLE
Clarify deprecation of `silenced` on datadog_monitor

### ISSUE THREAD

**Issue by martinb3** [terraform-providers/terraform-provider-datadog#389]
Hi there,

I'm looking for some clarification of the 'silencing by hand' section of the [datadog_monitor](https://www.terraform.io/docs/providers/datadog/r/monitor.html#silencing-by-hand-and-by-downtimes) documentation. It seems that setting `silenced` is [deprecated](https://github.com/terraform-providers/terraform-provider-datadog/pull/221/files), but it may still be populated and merged with current downtimes entered into the DD UI.

Is there a best practice/recommended way to say "don't remove existing downtimes" if they show up in the silenced map, as returned by the DD API? In other words, is there a way to do this, without referring to the deprecated `silenced` attribute:

```
resource "datadog_monitor" "foo" {
  lifecycle {
    ignore_changes = [silenced]
  }
}
```

Thanks in advance.

**Comment by bkabrda** [comment]
Hey @martinb3 👋 . You're exactly right, this is the way to do this. I'll send a PR to update documentation accordingly. Thanks for opening this issue!

**Comment by martinb3** [comment]
Thank you!!
