### ISSUE TITLE
Crash caused by passing list instead of map

### ISSUE THREAD

**Issue by rafe-delphix** [terraform-providers/terraform-provider-datadog#39]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.datadog v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
datadog_monitor

### Terraform Configuration Files

Please see the "silence" parameter. There is where I accidentally passed in a list where it should have been a map. The actual variable var.silenced is a map.

variable "silenced" {
  type = "map"
  default = {}
}

resource "datadog_monitor" "monitor" {

  name                 = "${data.template_file.env_label.rendered}${var.name}"

  type                 = "${var.type}"

  message              = "${var.message}"

  query = "${var.query}"
  
  include_tags         = "${var.include_tags}"
  require_full_window  = "${var.require_full_window}"
  locked               = "${var.locked}"
  no_data_timeframe    = "${var.no_data_timeframe}"
  notify_audit         = "${var.notify_audit}"
  notify_no_data       = "${var.notify_no_data}"
  renotify_interval    = "${var.renotify_interval}"
  timeout_h            = "${var.timeout_h}"

  thresholds = "${var.thresholds}"
  silenced = ["${var.silenced}"]

  tags = ["${var.tags}"]
}

### Debug Output

https://gist.github.com/rafe-delphix/b849d062840d458d975df30d8d4dc173
### Panic Output

https://gist.github.com/rafe-delphix/d0132ecf18ef07a7668bbe8d55cd0f7c

### Expected Behavior

Generate error message for user

### Actual Behavior

Crash with message on how to make crash report.

### Steps to Reproduce

terraform plan

**Comment by masci** [comment]
Closing as this is the expected behaviour
