### ISSUE TITLE
log_stream_definition widget doesn't understand new `indexes` field and breaks

### ISSUE THREAD

**Issue by carlosperello** [terraform-providers/terraform-provider-datadog#392]
### Terraform Version
Terraform v0.12.19
+ provider.datadog v2.5.0

### Affected Resource(s)
- datadog_dashboard

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "ecs_service_dashboard" {                                              
  count         = var.enable_datadog_dashboard ? 1 : 0                                              
                                                                                                    
  title         = "ECS Service '${var.service_name}' on cluster '${data.terraform_remote_state.ecs_cluster.outputs.ecs_cluster_name}' Dashboard"
  description   = "An autogenerated Dashboard from terraform for the ECS Service '${var.service_name}' running on the cluster '${data.terraform_remote_state.ecs_cluster.outputs.ecs_cluster_name}'"
  layout_type   = "free"                                                                            
  is_read_only  = true                                                                              
                                                                                                    
  widget {                                                                                          
    event_stream_definition {                                                                       
      query      = "sources:ecs,docker tags:task_name:${var.service_name},servicename:${var.service_name}"
      event_size = "s"                                                                              
    }                                                                                               
    layout = {                                                                                      
      height = 37                                                                                   
      width = 51                                                                                    
      x = 0                                                                                         
      y = 9                                                                                         
    }                                                                                               
  }
```

### Debug Output
It's not full output, just the important bit:

https://gist.github.com/carlosperello/37a47d7aec8ce40457f1b38a65b5c465

### Expected Behavior
The plan run should show that there was a new log_stream widget added to the dashboard which is not in terraform.

### Actual Behavior
It breaks with an unhelpful message (transport is closing)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add a Datadog dashboard from terraform
1. Edit the dashboard from Datadog and add a Log Stream widget from their site
1. Run a terraform plan
1. It breaks.

### Important Factoids
Nothing

### References
None

### Extra info

I found that the reason is because `Datadog` deprecated the use of `logset` so it's not there anymore, although the `datadog` provider sets it as mandatory, so I guess that's what causes the segfault. Now there is an `indexes` field which is a different type to hold what `logset` used to do.

If you add the widget from terraform everything works both ways, the problem is with an import / sync with a dashboard that has a log stream created from datadog's website.

**Comment by bkimbrough88** [comment]
I just ran into the same issue, would like to see logset not be required any more and a new indexes field added to reflect the current data structure for this widget.

**Comment by therve** [comment]
I reproduced the issue with `2.5.0`, and it seems it's now working with at `2.8.0`. Please reopen if it's not the case, thanks.
