### ISSUE TITLE
AWS integration update without replacement using new PUT method

### ISSUE THREAD

**Issue by isobit** [terraform-providers/terraform-provider-datadog#412]
@nmuesch mentioned in issue https://github.com/terraform-providers/terraform-provider-datadog/issues/335#issuecomment-540835825 that the PUT method for updating AWS integrations is now supported.

It appears that go-datadog-api already has functionality for calling this method (https://github.com/zorkian/go-datadog-api/blob/master/integrations.go#L271), similar to what was mentioned in this comment: https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_integration_aws.go#L176

Thought it would be worth creating an issue to track this as a feature request or enhancement. We have a large number of Datadog AWS integrations managed in terraform and it would nice to be able to update inherited host tags without forcing a full replacement and causing downtime.

**Comment by nmuesch** [comment]
Hey @isobit We just merged in a PR - https://github.com/terraform-providers/terraform-provider-datadog/pull/521 that introduces the `update` method into the AWS resource. This will be available in the next release of the provider. I'll go ahead and close out this issue for now but let us know if you experience any further issues here.
