### ISSUE TITLE
Missing legend_size on datadog_dashboard

### ISSUE THREAD

**Issue by matthewduren** [terraform-providers/terraform-provider-datadog#420]
The new datadog_dashboard resource does not include legend_size on widgets defined with timeseries_definition, like the datadog_screenboard resource used to include.

### Affected Resource(s)

datadog_dashboard

### Expected Behavior
There should be a way to set legend_size

### Actual Behavior
There is no way to set legend size

**Comment by dspatoulas** [comment]
I can see the property is in the code, may not be in the documentation yet.  Try passing in the `legend_size` property, it's a type string.
 
https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go

**Comment by matthewduren** [comment]
I had tried that first, actually, assuming the resource was cloned from the previous screenboard resource. Unfortunately it does not work, as subsequent plans still show legend_size being added.

Likely the same issue as #329.
