### ISSUE TITLE
[Bug] Unmarshal error for field Widget.title_size

### ISSUE THREAD

**Issue by zquestz** [terraform-providers/terraform-provider-datadog#422]
### Terraform Version
Terraform v0.12.21
+ provider.datadog v2.7.0

This also affects v2.5.0 of the datadog provider.

### Affected Resource(s)
Please list the resources as a list, for example:
- Widget.title_size

### Expected Behavior
Should run `terraform plan` without errors.

### Actual Behavior
`terraform plan` returns:

```
Error: json: cannot unmarshal string into Go struct field Widget.title_size of type int
```

### Steps to Reproduce
1. `terraform plan` with title_size defined on a widget. All title_size's in our repo are already ints, so I believe it's the recovery seeing them as strings.

**Comment by tobioboye** [comment]
I am also affected by this issue. Are there any workarounds? I have unfortunately upgraded my Terraform version and can't go back.

**Comment by agseijas** [comment]
@zquestz Is this happening on datadog_screenboard or datadog_dashboard resource ?
We had exactly the same issue, and it happened only when any of the affected dashboards were edited through Datadog browser UI. In this case the workaround was to taint the datadog resources and apply with `-refresh=false`. The solution might be to just migrate to the datadog_dashboard resource.

**Comment by enbashi** [comment]
Hi @zquestz , could you please list the name of the resource? `datadog_dashboard`, `datadog_screenboard` or `datadog_timeboard`? A snippet of the TR config that causes the issue can also help us reproduce and debug the issue faster.

**Comment by gzussa** [comment]
Closing this issue since there are no responses to previous questions.

`timeboard` and `screenboard` resources are deprecated and everyone should migrate to `dashboard`.
If this issue happens on deprecated resources, we most probably won't fix it.
If this issue happens on the `dashboard` resource, then feel free to reopen with more details on which widget is being affected.
