### ISSUE TITLE
datadog_monitor - Removal of 'tags' from resource has no effect

### ISSUE THREAD

**Issue by MattHodge** [terraform-providers/terraform-provider-datadog#43]
### Terraform Version
* Terraform v0.11.1
* provider.datadog v1.0.2

### Affected Resource(s)
* `datadog_monitor`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "foo" {
  name = "..."
  type = "metric alert"
  ...

  # The significant bit.
  tags = [ "foo:bar"]
}
```

Then remove the `tags` block:

```hcl
resource "datadog_monitor" "foo" {
  name = "..."
  type = "metric alert"
  ...
}
```

### Expected Behavior
* Terraform removes the monitors tags.

### Actual Behavior
Terraform says it is removing the tag, but it doesn't happen:

```bash
datadog_monitor.foo: Modifying... (ID: 3734291)
  tags.#: "1" => "0"
  tags.0: "foo:bar" => ""
datadog_monitor.foo: Modifications complete after 1s (ID: 3734291)
```

Re-run `terraform plan` and it still detects the tag:

```bash
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ datadog_monitor.script_runtime
      tags.#: "1" => "0"
      tags.0: "foo:bar" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```
Subsequent terraform plan invocations show the resources as out-of-sync, and subsequent terraform apply invocations end in the same result.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new Datadog monitor using Terraform with a tag.
1. Remove the tag and do an apply, which will not remove the tag.

**Comment by masci** [comment]
Fixed in #70
