### ISSUE TITLE
Unable to associate synthetic test with an SLO

### ISSUE THREAD

**Issue by matt-canty-dragon** [terraform-providers/terraform-provider-datadog#449]
### Terraform Version
v0.12.18

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_service_level_objective
- datadog_synthetics_test

### Terraform Configuration Files
```hcl
resource "datadog_synthetics_test" "example" {
  type    = "api"
  subtype = "http"
  request = {
    method = "GET"
    url    = "https://github.com/status"
  }
  request_headers = {
    Content-Type = "application/json"
  }
  assertions = [
    {
      type     = "statusCode"
      operator = "is"
      target   = "200"
    },
    {
      type     = "body"
      operator = "contains"
      target   = "GitHub lives!"
    }
  ]
  locations = ["aws:ap-southeast-1"]
  options = {
    tick_every = 300
  }
  tags    = []
  name    = "Test"
  message = "Test"
  status  = "live"
}

resource "datadog_service_level_objective" "example" {
  name        = "Test SLO"
  type        = "monitor"
  description = "Testing SLO with Terraform."
  monitor_ids = [datadog_synthetics_test.example.id]

  thresholds {
    timeframe = "7d"
    target    = "99"
    warning   = "99.5"
  }
}
```

### Debug Output
```
➜ terraform apply --auto-approve  
datadog_synthetics_test.example: Creating...
datadog_synthetics_test.example: Creation complete after 1s [id=nvr-sz3-gyy]

Error: Incorrect attribute value type

  on test.tf line 37, in resource "datadog_service_level_objective" "example":
  37:   monitor_ids = [datadog_synthetics_test.example.id]

Inappropriate value for attribute "monitor_ids": a number is required.
```

### Expected Behavior
It should create an SLO with a synthetic test as one of the attributed monitors.

### Actual Behavior
It fails because the SLO expects a list of numbers, but the synthetic test outputs it's ID as a string in the new format.

### Steps to Reproduce
```
terraform apply --auto-approve
```

### References
- https://github.com/zorkian/go-datadog-api/pull/219

**Comment by nmuesch** [comment]
Hey @matt-canty-dragon Thanks for the issue report. The synthetics resource includes a `monitor_id` element that should be able to be used in the SLO resource - https://www.terraform.io/docs/providers/datadog/r/synthetics.html#monitor_id

Could you try referencing the `monitor_id` field and see if that addresses your use case?

**Comment by matt-canty-dragon** [comment]
Thanks. I did not realise this. + it is in the docs!

It is working as expected.

**Comment by nmuesch** [comment]
No problem, glad to hear things are working!
