### ISSUE TITLE
[feature request] Allow datadog_dashboard to be used with json file

### ISSUE THREAD

**Issue by tspadi** [terraform-providers/terraform-provider-datadog#461]
Hi there,

I was wondering if it would be possible to implement dashboard management with datadog_dashboard, from a json document. This would allow to use datadog dashboards exported as json in our terraform codebase.

### Terraform Version
0.12.x

### Affected Resource(s)
- datadog_dashboard

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "my_dashboard" {
  config_json     = file("${path.module}/my_dashboard.json")
}
 ```

with my_dashboard.json contents being :
```json
{
    "notify_list": [
        "user@domain.com"
    ],
    "description": "A dashboard with memory info.",
    "template_variables": [
        {
            "default": "my-host",
            "prefix": "host",
            "name": "host1"
        }
    ],
    "is_read_only": true,
    "id": "qc9-tuk-9kv",
    "title": "Average Memory Free Shell",
    "url": "/dashboard/qc9-tuk-9kv/average-memory-free-shell",
    "created_at": "2019-02-05T01:06:36.636295+00:00",
    "modified_at": "2019-02-05T01:06:36.636295+00:00",
    "author_handle": "user@domain.com",
    "widgets": [
        {
            "definition": {
                "requests": [
                    {
                        "q": "avg:system.mem.free{*}"
                    }
                ],
                "type": "timeseries",
                "title": "Average Memory Free"
            },
            "id": 2252428653625902
        }
    ],
    "layout_type": "ordered"
}
``` 

Thanks

**Comment by tspadi** [comment]
What do you think about this proposal ? 
Does it make sense to implement this feature in the datadog provider for the dashboard resource ?

**Comment by jirikuncar** [comment]
Hi @tspadi, would a resource import for you - https://www.terraform.io/docs/state/import.html?

**Comment by tspadi** [comment]
Hi @jirikuncar, this would only allow me to build terraform state. I'd like to be able to manage a dashboard providing a json document in the resource as described above.

**Comment by jirikuncar** [comment]
@tspadi and what about converting the json file to [JSON Configuration Syntax](https://www.terraform.io/docs/configuration/syntax-json.html)? I am not sure if having a JSON object in the state is desirable while working with Terraform.

**Comment by tspadi** [comment]
Hello @jirikuncar, this would work as a workaround, but that's not exactly what we had in mind. In fact, we thought about something like in the grafana provider,  grafana_dashboard resource to be implemented : https://www.terraform.io/docs/providers/grafana/r/dashboard.html#config_json
We'd be glad to contribute implementing the same kind of feature for datadog_dashboard resource, as it would be relevant for us.

**Comment by bendrucker** [comment]
Have you tried this?

https://github.com/GoogleCloudPlatform/terraformer#use-with-datadog

It reads the config schema directly from the provider plugin:

https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/provider_wrapper/provider.go

Supporting a JSON attribute in the existing resource means that the existing required fields would need to be made optional. Merging JSON and HCL is a good user experience (e.g. `source_json`, but it requires an API to include IDs with each list item:

https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html

It would get messy to try to add this to the existing resource. Does `config_json` conflict with every other attribute? Just widget? Do you try to merge the attributes with the JSON? 

This comes up for a lot of providers and is often declined (e.g. Kubernetes). Some users choose to use custom providers. If there were is one resource where it makes sense, it's definitely dashboards. I would stop short of extending that to monitors though. I think a new resource is the best fit for that with just the single attribute. There's still an opportunity to merge in new values from HCL by using `jsondecode`, `merge`, and `jsonencode`.

**Comment by gzussa** [comment]
Hi @tspadi, This is not a feature we will implement at the moment. Like described by @bendrucker there are alternatives and it is not common practice in general. 

However, we added testing files per widget definition. They include both the JSON and yaml config. For example: https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard_alert_graph_test.go#L9-L71. This should help you better understand how to craft your config.
