### ISSUE TITLE
[Feature Request] External log archive resource

### ISSUE THREAD

**Issue by opalmer** [terraform-providers/terraform-provider-datadog#466]
Hi,

It appears that external [log archives](https://docs.datadoghq.com/logs/archives/) aren't currently supported by the Terraform provider. It also looks like there's [no API documentation for archives](https://docs.datadoghq.com/api/) right now but DataDog's portal uses an API under the hood (example below) so I'm assuming it could be turned into a Terraform resource potentially.

Couple of questions here:
* Are there any plans to support creating external log archives with Terraform?
* If someone were to contribute to this effort, is there documentation for the API DataDog is using to manage external log archives?

### Request
```
POST https://app.datadoghq.com/api/v1/logs/external_archives
{
  "name": "test-archive",
  "query": "<REDACTED>",
  "destination": {
    "type": "s3",
    "bucket": "<REDACTED>,
    "path": "",
    "integration": {
      "accountId": "<REDACTED>",
      "roleName": "<REDACTED>"
    }
  },
  "_authentication_token": "<REDACTED>"
}
```
### Response
```json
{
  "id": "<REDACTED>",
  "name": "test-archive",
  "state": "UNKNOWN",
  "query": "<REDACTED>",
  "enabled": true,
  "destination": {
    "bucket": "<REDACTED>",
    "path": "",
    "integration": {
      "accountId": "<REDACTED>",
      "roleName": "<REDACTED>"
    },
    "type": "s3"
  }
}
```

**Comment by PierreVanRoy** [comment]
Hello, 

Thanks for reaching us.

> Are there any plans to support creating external log archives with Terraform?

We are currently working on the Archive APIs (including Terraform support).
We are waiting to have everything properly tested to update our documentation. 
I have no precise ETA for this but it will be available by the end of the quarter. 

> If someone were to contribute to this effort, is there documentation for the API DataDog is using to manage external log archives?

As said above, the documentation will come with the official support of API related external Archive.



Pierre

**Comment by jaredready** [comment]
Another interested party here. We're just a few days out from the end of the quarter. Is this still on track to be released soon? Can the community offer any help?

Thanks!

**Comment by jirikuncar** [comment]
@jaredready there is already a WIP PR #544.

**Comment by gzussa** [comment]
This feature will be part of `v2.11.0` we will release next week.
