### ISSUE TITLE
Feature request: excluded_regions support for AWS integration resource

### ISSUE THREAD

**Issue by isobit** [terraform-providers/terraform-provider-datadog#468]
The AWS integration create/update API supports an `excluded_regions` parameter for specifying regions to exclude from metrics collection. Right now this is only configurable through direct API calls, it would be great if this could be controlled using the terraform resource as well.

I did notice the AWS integration list API (`GET /v1/integration/aws`) response does not include an `excluded_regions` property, so this might be contingent on some API changes in order to implement state refreshing: https://docs.datadoghq.com/api/?lang=bash#list-all-aws-integrations

**Comment by snazzyfox** [comment]
After playing with the API manually, it looks like `excluded_regions` is actually available in the GET integrations API, just undocumented (yet). An example response I got

```json
        {
            "role_name": "role-name",
            "excluded_regions": [],
            "account_id": "123456789012",
            "host_tags": [
                "environment:qa"
            ],
            "account_specific_namespace_rules": {
                "elb": true,
                "sns": true
            },
            "errors": [],
            "filter_tags": []
        },
```

It would be great if datadog can guarantee the existence of this field (by updating their docs), but for now it doesn't look like it will block someone from implementing this feature.

**Comment by vibhuyadav** [comment]
Yeah, we had to use POST/PUT calls to add excluded_regions to our integrations. We have multiple accounts and this helped us save some costs. The problem with POST is that it creates new External_IDs which makes the integration break. Currently we are running bash scripts inside Terraform to do this but it's not working as expected.
```
provisioner "local-exec" {
    command = <<EOT
    curl -X PUT -w '\n' -H "Content-type: application/json" -H "DD-API-KEY: ${var.datadog_api_key}" -H "DD-APPLICATION-KEY: ${var.datadog_app_key}" -d '{ "excluded_regions": ["us-west-2",.....]}' "https://api.datadoghq.com/api/v1/integration/aws?account_id=${data.aws_caller_identity.current.account_id}&role_name=${aws_iam_role.test_role.name}"
  EOT
  }
