### ISSUE TITLE
[feature request] Allow datadog_monitor to be used with exported monitor JSON definition

### ISSUE THREAD

**Issue by ianwsperber** [terraform-providers/terraform-provider-datadog#470]
Feature request to allow defining the `datadog_monitor` resource using the JSON definition exported from the datadog web console.

I would like to be able to create and update monitors using Datadog's intuitive UI, then move these monitors to terraform using the JSON export of the monitor. The JSON export exists so that there is an intuitive and reusable definition of the monitor than may be shared in eg CI, so it makes sense that we should be able to use this standard definition in Terraform

Defining monitors using HCL has several drawbacks
- Cannot create monitor using intuitive UI
- Monitor terraform resource does not support all feature supported by monitors, while JSON def always has parity
- Requires team to learn another bespoke configuration syntax
- Cannot use otherwise standard JSON definition of monitor

### Terraform Version

0.12.x

### Affected Resource(s)

- `datadog_monitor`

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "my_monitor" {
  config_json     = file("${path.module}/my_monitor.json")
}
```

### References

- Equivalent feature request to #461

**Comment by gzussa** [comment]
Using whole JSON as configuration is not something we will implement since it will make issue troubleshooting very difficult.
