### ISSUE TITLE
Timezones are not recognized on Windows computers for datadog_downtime

### ISSUE THREAD

**Issue by nrjohnstone** [terraform-providers/terraform-provider-datadog#473]
### Terraform Version
v0.12.17

### Affected Resource(s)
datadog_downtime

### Expected Behavior
I should be able to specify any IANA timezone name when creating a datadog downtime.

### Actual Behavior
Specifying anything other than "UTC" leads to the complaint from the datadog provider that it is not a IANA timezone name.

Have tried Europe/Amsterdam and a bunch of others that should be recognized.

### Steps to Reproduce
Create a simple datadog down resource with a non UTC timezone and run it on a Windows box.

### References
I believe this issue in the go time library indicates the point that on Windows you needed to include the timezone library manually for time to work correctly with zones.

https://github.com/golang/go/issues/21881

Should be fixed by linking the timezones into the provider as the latest comments seem to suggest.

**Comment by timhill-iress** [comment]
I think it's worse than reported. I'm using Ubuntu and have Go installed.

Only UTC and (local or localtime) are supported. https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_downtime.go#L487

When local or localtime is used then the provider gets the current timezone and then tries to validate it. Unfortunately, it uses the validteDatdogDowntimeRecurrenceType routine https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_downtime.go#L495

So in effect only UTC will work.

**Comment by nrjohnstone** [comment]
I've actually given up on using terraform for downtime, as the way datadog treats downtime seems to be by deleting and recreating the downtime each day. And also, each time you rerun the same terraform script a day later, it complains that the downtime is in the past.
Until datadog can fix the way that downtime resources are specified and treated, I think having them as config seems to be too much hassle.

**Comment by timhill-iress** [comment]
@nrjohnstone as shown in the tests ( https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_downtime_test.go#L411 ) , I'm dating my downtime in the future i.e. 2099. As my downtime is daily, only the time component of the date is relevant to me. I've not come across the other problems you mention just yet, but I've only started with terraform and datadog.
