### ISSUE TITLE
[Feature Request] Allow insecure certificates

### ISSUE THREAD

**Issue by mattcanty** [terraform-providers/terraform-provider-datadog#475]
Synthetics tests created via the UI let you allow insecure certiticates. This property is exposed via the Datadog API as `allow_insecure`.

go-datadog-api does not support it yet so I have [raised a ticket there](https://github.com/zorkian/go-datadog-api/issues/322) for this issue as well.

**Comment by nsuarezcanton** [comment]
I've opened a PR such that we have support for this in `go-datadog-api`. From there, we'll be able to update the provider. Thanks for bringing this up!

**Comment by matt-canty-dragon** [comment]
@nsuarezcanton any update on this being fixed in the provider too?

**Comment by gzussa** [comment]
Hi, we are migrating the resource to use our new official Go client (beta version) https://github.com/DataDog/datadog-api-spec. We are deprecating the `go-datadog-api` dependency. It will be included in the next release coming soon.

**Comment by slavogiez** [comment]
Hi @gzussa, any update about the new provider release? Thanks!

**Comment by gzussa** [comment]
Hi, It's already on master and we will make a release next week or the week after. I am closing this issue but feel free to reopen if needed.

**Comment by gzussa** [comment]
Sorry reopening
