### ISSUE TITLE
Query contains unbalanced parenthesis Passes terraform validate/plan but fails on apply

### ISSUE THREAD

**Issue by tmack8001** [terraform-providers/terraform-provider-datadog#48]
### Terraform Version

```
$ terraform version
Terraform v0.11.3
+ provider.datadog v1.0.3
+ provider.template v1.0.0
```

### Expected Behavior
When the query parameter in a monitor / timeboard / etc isn't well formed the terraform validate step should fail.

### Actual Behavior
When there are unbalanced parenthesis in the query parameter of a monitor the terraform validate and terraform plan tasks aren't failed and only upon terraform apply (hitting the DD API does it fail).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a monitor similar to the following (actual metrics data removed for sensitive reasons):
```
resource "datadog_monitor" "my-monitor-monitor" {
  name = "My Monitor Name"
  type = "query alert"

  message = "${data.template_file.my-monitor.rendered}"

  query = "min(last_5m):sum:counter.error{mytag:mytagvalue} by {environment}.as_count() / ( sum:counter.error{mytag:mytagvalue} by {environment}.as_count() + sum:counter.success{mytag:mytagvalue} by {environment}.as_count() ) ) * 100 > ${var.my-monitor-critical}"

  thresholds {
    warning = "${var.warning}"
    critical = "${var.critical}"
  }

  require_full_window = false
  notify_no_data = false
  renotify_interval = 15

  notify_audit = false
  timeout_h = 0
  include_tags = true
  tags = ["terraform"]
}

data "template_file" "my-monitor" {
  template = "${file("${path.module}/templates/my-monitor.tpl")}"
  vars {
    notification_channel = "${var.pager_duty}"
  }
}
```
1. `terraform validate`  (passes)
1. `terraform plan`    (passes)
1. `terraform apply`   (fails with below)
```
* module.datadog_monitor.my-monitor-monitor: 1 error(s) occurred:
* datadog_monitor.my-monitor-monitor: error updating monitor: API error 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}
```

The problem in the query is the unbalanced parenthesis so a working version of the monitor should have this instead... and I believe there should be some syntax / well formed checks in the validate stage. Below is the corrected monitor query.
```
query = "min(last_5m):sum:counter.error{mytag:mytagvalue} by {environment}.as_count() / ( sum:counter.error{mytag:mytagvalue} by {environment}.as_count() + sum:counter.success{mytag:mytagvalue} by {environment}.as_count() ) * 100 > ${var.my-monitor-critical}"
```

**Comment by yfronto** [comment]
The [Datadog API](https://docs.datadoghq.com/api/) doesn't provide a mechanism to validate a query. If we write validation that looks for unmatched parens, it's only one possible of validation error. Other things, like misspelling a metric or aggregation function, would still be missed.

Unless Datadog adds a validation endpoint or publishes a full grammar for their queries, it's unrealistic to validate queries client-side.

**Comment by masci** [comment]
I agree with @yfronto, my considerations are the same you can read in #66
