### ISSUE TITLE
aggregator ignored for query_value on timeboards

### ISSUE THREAD

**Issue by dustinblackman** [terraform-providers/terraform-provider-datadog#49]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.3
+ provider.datadog v1.0.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_timeboard

### Terraform Configuration Files
```hcl
resource "datadog_timeboard" "testboard" {
  title       = "testboard"
  description = "testboard"
  read_only   = true

  graph {
    title     = "Success Percentage"
    viz       = "query_value"
    precision = 3

    request {
      q          = "sum:int.request.successful{*}.as_count()/sum:int.request.count{*}.as_count()"
      aggregator = "min"
    }
  }
}
```

### Debug Output
https://gist.github.com/dustinblackman/639422d1baec7a8d5cdcf8c0ab4b6369

### Expected Behavior

Requests `aggregator` should be set to `min`.

### Actual Behavior

`aggregator` is completely ignored and the default of `avg` is set on the datadog dashboard.
![example](https://i.imgur.com/1X5awQU.png)

### Steps to Reproduce
1. Copy example above to test file
2. Replace metrics with something that exist in your datadog account
3. `terraform apply`

### Important Factoids
- None

**Comment by dustinblackman** [comment]
Actually turns out this may be a Datadog UI bug as looking at the requests made, it is in fact doing `min` on the request, but gets reset in the edit view. Is there possibly defaults missing that resets their UI?

**Comment by nmuesch** [comment]
Hey @dustinblackman I'm sorry for not responding sooner here. I just tested this on the latest provider (thanks for the example config) and I wasn't able to reproduce. Are you still experiencing this issue?

**Comment by dustinblackman** [comment]
No worries! Looks fine now, thanks!
