### ISSUE TITLE
Support for composite monitor update/delete order and force delete

### ISSUE THREAD

**Issue by vish91** [terraform-providers/terraform-provider-datadog#519]
### Terraform Version
Terraform v0.12.26
+ provider.datadog v2.7.0

### Affected Resource(s)
- datadog_monitors

### Expected Behavior
Given a terraform plan with an update to a composite monitor and a delete for individual monitor used by that composite monitor. 
It should be able to successfully delete the individual monitor and update the composite monitor to not use that deleted monitor.
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy
```

### Actual Behavior
Since composite monitor is still using a reference to the monitor ID that we are trying to delete it fails the terraform apply altogether. 
1. No way to order the steps to make sure it updates the composite monitor before deleting inidividual monitor
2. No way to force delete a monitor using terraform like we can from the API or other sdks.
https://docs.datadoghq.com/api/v1/monitors/#delete-a-monitor

```
Error: 400 Bad Request: {"errors":["Monitor is part of the following composite monitors] .....

Error: API error 401 Unauthorized: {"errors":["monitor [xxxxYYYY, [monitor-A] is referenced in monitor-B]"]}
```

**Comment by ykyr** [comment]
I have exact same issue. 
However, even-though `datadog_monitor` is missing such an attribute,  I think this is datadog side issue. 

I'm not able to force delete the monitor via API:
`curl -X DELETE "https://api.datadoghq.com/api/v1/monitor/${monitor_id}?force=true&api_key=${api_key}&application_key=${app_key}"`
```
{"errors":["Monitor is part of the following composite monitors: Test composite"]}
```

Documentation with `force=True` was added in this MR https://github.com/DataDog/documentation/pull/6595

**Comment by ykyr** [comment]
After communication with Datadog support, their engineering team fixed the API. 
I opened a pull request to add `force_delete` parameter to `datadog_monitor` resource.

**Comment by vish91** [comment]
@ykyr thanks for your help and fixing this.
