### ISSUE TITLE
Screenboard resource

### ISSUE THREAD

**Issue by bentterp** [terraform-providers/terraform-provider-datadog#52]
Hi,
I'd really like to be able to terraform a screenboard with my terraformed monitors in. I feel that's the missing part of the puzzle.

https://godoc.org/gopkg.in/zorkian/go-datadog-api.v2#Screenboard

**Comment by masci** [comment]
Going to schedule some work to support this as soon as I finish adding user access roles.

**Comment by skyzyx** [comment]
This appears to have been added in https://github.com/terraform-providers/terraform-provider-datadog/releases/tag/v1.3.0.

**Comment by masci** [comment]
Forgot to close this, fixed in #91
