### ISSUE TITLE
400 from datadog when provisioning an SLO.

### ISSUE THREAD

**Issue by AlanKavanagh** [terraform-providers/terraform-provider-datadog#520]
Hi Guys, We get the following error when trying to provision an SLO on V1 endpoints. 
`API error 400 Bad Request: {"errors": ["Invalid payload: Required parameter 'slo' is missing"]}`

We are using latest terraform and datadog provider and the resource is configured per the documentation. The same issue occurs for both Metric and Monitor Type SLOs.

Thanks for any guidance you can provide.

**Comment by gzussa** [comment]
Hi, I am not able to reproduce the issue. 
Would you be able to share a config I could use in a test?

**Comment by AlanKavanagh** [comment]
Hi @gzussa  I can't spot anything drastically different than any other SLOs, it occurs for both metric and monitor type slos. I've attached a sample of the format we use. Please let me know if I can be anymore help.

`resource "datadog_service_level_objective" "service_errors" {
  name               = "${local.service_name}: Service Error rate"
  type                 = "monitor"
  description     = "${local.service_name}: Service Error Rate SLO"
  monitor_ids    = ["${datadog_monitor.service_errors.id}"]
  thresholds {
    timeframe = "7d"
    target = 0
    warning = 10
  }

  tags = ["${local.service_name}:slo", "slo:${local.service_name}"]
}`

**Comment by therve** [comment]
I reproduced on 2.7.0, and the test I used worked on 2.8.0. Can you upgrade and check that it works for you? Please reopen if it doesn't, thanks!

**Comment by AlanKavanagh** [comment]
Will do, thanks @therve
