### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by skang0601** [terraform-providers/terraform-provider-datadog#526]
Hi there,
It looks like https://github.com/terraform-providers/terraform-provider-datadog/issues/318 issue has been resolved with a new resource to provision the logs collection lambda `datadog_integration_aws_log_collection`. Could a new release be published for the Terraform provider so we can start using this resource?

Thanks in advance.

**Comment by gzussa** [comment]
Hi, it is now done. Checkout ou v2.8.0. Thanks
