### ISSUE TITLE
GRPCProvider "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by stefanax** [terraform-providers/terraform-provider-datadog#534]
Running Terraform apply crashes when refreshing resources.

It starts to refresh resources just fine, but suddenly it crashes with an error. (see log below)

In our case we have a datadog_monitor resource in which we have a for_each argument. Thus each monitor created should be basically identical to each other, any difference is either a target value or a small textblock (a-zA-Z). So no strange characters or similar.

This worked well a couple of days ago (I'd guess it used 2.7 then)

### Terraform Version
Terraform v0.12.25
+ provider.datadog v2.8.0

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
(I know this is not the whole file. Do not have time to clean out "corporate secrets" as of now. I can add stuff if needed)
```hcl
resource "datadog_monitor" "kubernetes_service_memory_vs_limit" {
  for_each = {
    for key, value in var.kubernetes_services_monitors:
    key => value
    if contains(keys(value), "memory_limit")
  }
  
  name              = "${upper(var.namespace)} ${var.kubernetes_services[each.key]["name"]} Memory vs Limit in Percent"
  type              = "query alert"
  message           = "{{#is_alert}}${var.kubernetes_services[each.key]["name"]} Memory is close to it's Limit. GO FIX! ${var.notification_error} {{/is_alert}} \n{{#is_recovery}}${var.kubernetes_services[each.key]["name"]} Memory vs Limit should be back to normal again. ${var.notification_error} ${var.notification_warning}{{/is_recovery}} ${var.notification_teams_backend} "
  
  query             = "avg(last_15m):(sum:kubernetes.memory.usage{kube_namespace:${var.namespace},kube_deployment:${each.key}} by {pod_name}/max:kubernetes.memory.limits{kube_namespace:${var.namespace},kube_deployment:${each.key}} by {pod_name})*100 > ${each.value["memory_limit"]["critical"]}"
  
  thresholds = {
    critical          = each.value["memory_limit"]["critical"]
    critical_recovery = each.value["memory_limit"]["critical_recovery"]
  }
  
  notify_no_data    = false
  renotify_interval = 0
  locked            = true
  
  tags              = ["terraform", "customer:${var.namespace}"]
}
```

### Panic Output
https://gist.github.com/stefanax/d82375850cf7d5e7e17667895d741d15

### Expected Behavior
Terraform refreshing all resources as normal.

### Actual Behavior
Crash during refresh on some "random" resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply --var-file=variable-file.tfvars`

**Comment by nmuesch** [comment]
Hey @stefanax Thanks for the issue report, and apologies for the inconvenience here. 
Based on the panic report shared, it looks like the issue is coming from a dashboard resource with a Log Stream widget.

While I work on investigating the issue further, could you share the config for the dashboard resource that includes this log stream widget (removing any potential secrets).

**Comment by stefanax** [comment]
`resource "datadog_dashboard" "customer_overview" {
  title        = "${upper(var.namespace)} Overview"
  description  = "Some description here"
  layout_type  = "free"
  is_read_only = true

  widget {
    timeseries_definition {
      title = "CPU cores used"
      
      request {
        q = "sum:kubernetes.cpu.usage.total{kube_namespace:${var.namespace}}/1000000000"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
      yaxis {
        min = 0
      }
    }
    layout = {
      x      = 0
      y      = 0
      width  = 71
      height = 15
    }
  }

  widget {
    timeseries_definition {
      title = "Memory used"
      
      request {
        q = "sum:kubernetes.memory.usage{kube_namespace:${var.namespace}}"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
      yaxis {
        min = 0
      }
    }
    layout = {
      x      = 0
      y      = 15
      width  = 71
      height = 15
    }
  }

  widget {
    timeseries_definition {
      title = "Network usage (pod RX)"
      
      request {
        q = "avg:kubernetes.network.rx_bytes{*}"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
      yaxis {
        min = 0
      }
    }
    layout = {
      x      = 0
      y      = 30
      width  = 71
      height = 15
    }
  }

  widget {
    timeseries_definition {
      title = "Ingress Throughput"
      
      request {
        q = "sum:trace.nginx.handle.hits{service:${var.namespace}-ingresscontroller}.as_count()"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
      yaxis {
        min = 0
      }
    }
    layout = {
      x      = 72
      y      = 0
      width  = 71
      height = 15
    }
  }

  widget {
    timeseries_definition {
      title = "Traffic difference (1 week)"
      
      request {
        q = "sum:trace.nginx.handle.hits{service:${var.namespace}-ingresscontroller}.as_count()-week_before(sum:trace.nginx.handle.hits{service:${var.namespace}-ingresscontroller}.as_count())"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 72
      y      = 15
      width  = 71
      height = 15
    }
  }

  widget {
    timeseries_definition {
      title = "Throughput distribution per service"
      
      request {
        q = "sum:trace.nginx.handle.hits{service:${var.namespace}-ingresscontroller} by {resource_name}.as_count()"
        display_type = "area"
        style {
          palette    = "dog_classic"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 72
      y      = 30
      width  = 71
      height = 15
    }
  }

  widget {
    query_value_definition {
      request {
        q = "sum:kubernetes.pods.running{kube_namespace:${var.namespace}}"
        aggregator = "last"
      }
      title     = "Pods running"
      autoscale = false
      precision = 0
    }
    layout = {
      x      = 0
      y      = 46
      width  = 35
      height = 15
    }
  }

  widget {
    query_value_definition {
      request {
        q = "sum:kubernetes_state.deployment.replicas_unavailable{namespace:${var.namespace}}+(sum:kubernetes_state.statefulset.replicas_desired{namespace:${var.namespace}}-sum:kubernetes_state.statefulset.replicas_ready{namespace:${var.namespace}})"
        aggregator = "last"
        conditional_formats {
            comparator = ">"
            value = "0"
            palette = "white_on_red"
        }
      }
      title     = "Pods not ready"
      autoscale = false
      precision = 0
    }
    layout = {
      x      = 36
      y      = 46
      width  = 35
      height = 15
    }
  }

  widget {
    query_value_definition {
      request {
        q = "sum:kubernetes_state.job.succeeded{namespace:${var.namespace}}.as_count()"
        aggregator = "last"
      }
      title     = "Successful Jobs"
      autoscale = false
      precision = 0
    }
    layout = {
      x      = 0
      y      = 62
      width  = 35
      height = 15
    }
  }

  widget {
    query_value_definition {
      request {
        q = "sum:kubernetes_state.job.failed{namespace:${var.namespace}}.as_count()"
        aggregator = "last"
        conditional_formats {
            comparator = ">"
            value = "0"
            palette = "white_on_red"
        }
      }
      title     = "Failed Jobs"
      autoscale = false
      precision = 0
    }
    layout = {
      x      = 36
      y      = 62
      width  = 35
      height = 15
    }
  }

  widget {
    manage_status_definition {
      color_preference = "text"
      display_format = "countsAndList"
      hide_zero_counts = true
      query = "tag:terraform AND tag:customer:${var.namespace} AND status:(alert OR warn)"
      show_last_triggered = false
      sort = "status,asc"
      summary_type = "monitors"
      title_size = 13
      title_align = "left"
      count = 1000
    }
    layout = {
      x      = 72
      y      = 46
      width  = 71
      height = 31
    }
  }
  
  widget {
    log_stream_definition {
      logset = "1"
      query = "kube_namespace:${var.namespace}"
      columns = ["service"]
    }
    layout = {
      x      = 0
      y      = 78
      width  = 143
      height = 36
    }
  }
}`

**Comment by nmuesch** [comment]
Thanks @stefanax Looking at that, I believe PR #536 will resolve your issue as it'll properly allow indexes to not be required in the logstream widget
