### ISSUE TITLE
datadog_ip_ranges undefined response type

### ISSUE THREAD

**Issue by kamsz** [terraform-providers/terraform-provider-datadog#537]
In recent days datadog_ip_ranges data resource started to fail.

Error: undefined response type

  on .terraform/modules/skeleton/app/ec2.tf line 11, in data "datadog_ip_ranges" "this":
  11: data "datadog_ip_ranges" "this" {}

**Comment by nmuesch** [comment]
Hey @kamsz Thanks for the issue report. I wasn't able to reproduce by specifying a `datadog_ip_ranges` data source in a local config. 

Could you share the version of terraform you're using, the config where this data source is being used, and the full error trace if possible (excluding any sensitive information).

**Comment by kenorb** [comment]
Same error here.

```
$ terraform refresh
Acquiring state lock. This may take a few moments...
...
Error: undefined response type

  on nsg_kibana.tf line 134, in data "datadog_ip_ranges" "main":
 134: data "datadog_ip_ranges" "main" {}


Releasing state lock. This may take a few moments...
```

Versions:
```
% terraform -version
Terraform v0.12.26
+ provider.azurerm v2.14.0
+ provider.datadog v2.8.0
```

Definition:
```
data "datadog_ip_ranges" "main" {}
```

Used syntax:
```
data.datadog_ip_ranges.main.synthetics_ipv4
```

**Comment by kenorb** [comment]
This looks like the regression, since it works fine with `v2.7.0`.
