### ISSUE TITLE
Datadog Timeboard: Metadata key

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-datadog#61]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.8.0
+ provider.datadog v1.0.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- https://www.terraform.io/docs/providers/datadog/r/timeboard.html

### Terraform Configuration Files
Trying to take the JSON config from a dashboard I created in Datadog, and port it to HCL so that I can manage it with Terraform. It appears that the `metadata` key is not supported yet by this provider.

The JSON config for Datadog is:

```json
{
  "requests": [
    {
      "q": "sum:aws.trustedadvisor.green_checks, sum:aws.trustedadvisor.yellow_checks, sum:aws.trustedadvisor.red_checks",
      "type": "bars",
      "style": {
        "palette": "dog_classic",
        "type": "solid",
        "width": "normal"
      },
      "metadata": {
        "sum:aws.trustedadvisor.green_checks": {
          "alias": "OK"
        },
        "sum:aws.trustedadvisor.yellow_checks": {
          "alias": "WARN"
        },
        "sum:aws.trustedadvisor.red_checks": {
          "alias": "ERROR"
        }
      },
      "conditional_formats": []
    }
  ],
  "viz": "timeseries",
  "autoscale": true
}
```

**Comment by vineethvijay** [comment]
+1
This would be a nice feature to have, for making meaningful metadata over the graph rather than the query metric names.

**Comment by LozanoMatheus** [comment]
+1

**Comment by andreitchaltsev** [comment]
+1 to the feature. 
For complicated queries the formulas may be unreadable. Having nice alias would be very helpful.

**Comment by andreafalzetti** [comment]
Anyone looking into this?

**Comment by cyprianos** [comment]
+1

**Comment by michaelfoley1** [comment]
+1

**Comment by trp956s** [comment]
+ 1

**Comment by JohnB** [comment]
+111

**Comment by infrat** [comment]
+1

**Comment by bkabrda** [comment]
Hey folks, I'm working on this right now. As the first step, I opened a PR to add support to the go client library: https://github.com/zorkian/go-datadog-api/pull/241 - implementing this in the provider should be pretty easy after that PR is accepted.

**Comment by bkabrda** [comment]
So I seem to be running into an issue with complex nested structures with terraform trying to implement this in the provider. Basically it seems I'm hitting [1]. I'm currently in discussion with Hasicorp folks to figure out a workable solution for this case. I'll keep this issue updated with the progress. Thanks for your patience everyone!

[1] https://github.com/hashicorp/terraform/issues/6215
