### ISSUE TITLE
Missing query validation on plan

### ISSUE THREAD

**Issue by eredi93** [terraform-providers/terraform-provider-datadog#66]
I fell that the Datadog provider is not doing proper sanity checks on plan.
In my opinion, during plan i should get an error if the resource is misconfigured.
Currently, i'm getting failures on apply due stupid mistakes i make, i think they could be checked during plan.

Examples:
* threshold: the critical threshold must match the one in the query should be easy enough to check that the digits matches during plan
* query check: apparently some parameter combinations are not accepted, a query sanity check would be nice to have

A few example of my failures:

## threshold issue

plan
```
+ datadog_monitor.xxxxxxxxxxxxxxxxxxx
    locked:              "true"
    message:             "xxxxxxxxxxxxxxxxxxx"
    name:                "xxxxxxxxxxxxxxxxxxxxxx"
    no_data_timeframe:   "10"
    notify_audit:        "false"
    notify_no_data:      "true"
    query:               "sum(last_5m):avg:production.xxxxx.xxxxxx.count{target:xxxx-xxx-xxxxxx-xxxx}.as_count()"
    tags.%:              "1"
    tags.terraform:      "true"
    thresholds.%:        "1"
    thresholds.critical: "1"
    timeout_h:           "0"
    type:                "metric alert"


Plan: 1 to add, 0 to change, 0 to destroy.
```

apply

```
Error applying plan:

1 error(s) occurred:

* datadog_monitor.xxxxxxxxxxxxxxxxxxx: error updating montor: API error 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

## query check issue

plan
```
+ datadog_monitor.foo
    locked:              "true"
    message:             "xxxxxxxxxxxxxxxxxxx"
    name:                "xxxxxxxxxxxxxxxxxxxxxx"
    no_data_timeframe:   "10"
    notify_audit:        "false"
    notify_no_data:      "true"
    query:               "avg(last_5m):avg:production.xxxxx.xxxxxx.count{*}.as_count() <= 1"
    tags.%:              "1"
    tags.terraform:      "true"
    thresholds.%:        "1"
    thresholds.critical: "1"
    timeout_h:           "0"
    type:                "metric alert"


Plan: 1 to add, 0 to change, 0 to destroy.
```

apply

```
Error applying plan:

1 error(s) occurred:

* datadog_monitor.foo: error updating montor: API error 400 Bad Request: {"errors":[".as_count() monitors must use the 'sum'/'in total' time aggregator"]}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I'd love to get this failure on plan. Don't really have much experience with writing providers, Do you think it can be done?

**Comment by masci** [comment]
I'm closing as won't fix because I think Terraform's responsibility ends when it verifies whether a required argument like `query` is present or not at plan time. Checking the correctness of the query requires replicating the same validation Datadog performs in the API itself and this is hard to implement, maintain and extend to other arguments that require validation.

I know this is frustrating as the threshold issue bit me as well, I'll take another pass at docs to make evident that you can't just copy the query from Datadog UI and paste into the `query` argument.

**Comment by eidge** [comment]
This is affecting me as well. Wild thought, wouldn't it be possible for you guys to have a `/validate` endpoint and have terraform plan call that?

That way you wouldn't have to duplicate all logic in terraform and we could still have some sanity checking.

I've got no way if this is possible with terraform though.

**Comment by krish7919** [comment]
> I know this is frustrating as the threshold issue bit me as well, I'll take another pass at docs to make evident that you can't just copy the query from Datadog UI and paste into the query argument.

How does one get the query then?

**Comment by roopakv** [comment]
So in certain aws cases if you enter invalid data, plan does complain. Why is this any different? I am happy to find and provide examples where the terraform aws module does do validations.
