### ISSUE TITLE
Feature Request: AWS Integration

### ISSUE THREAD

**Issue by iancward** [terraform-providers/terraform-provider-datadog#76]
Hi there,
The Datadog API [supports](https://docs.datadoghq.com/api/?lang=python#aws) configuration of the AWS integration; it would be nice to have  the ability to configure it here.

**Comment by iancward** [comment]
Support for this was recently added as part of release v2.11.0 in go-datadog-api.
I notice that the go-datadog-api vendored module is the only vendored module pulled via gopkg.in. Does it make sense to migrate the vendor.json to just pull the tag directly from github.com?

**Comment by masci** [comment]
Hi @iancward 
probably a naive question but how that would be better? I'd need to change all the imports, not a big deal but curious about what we get in exchange.

**Comment by iancward** [comment]
Ah, I see what you mean about having to change all the imports. I think I was mostly looking to get the vendored dependencies pulled from the same place (github.com) rather than some being pulled directly from github.com (which, via tags, lets you pin specifically to a minor release) and some being pulled from the third-party gopkg.in site.

If you're amenable to this change, I can submit a PR (assuming all tests pass) with the updated vendor.json and imports. I'm just waiting for my employer to approve me to contribute to this project.

**Comment by masci** [comment]
I see, thanks! No objections from my side to vendor the `github.com/` import path 👍 I do agree that would make tracking more explicit.

**Comment by iancward** [comment]
Ok, feel free to take a look at #84. I'll start working on the AWS integration.

**Comment by masci** [comment]
Update: some work is going on at https://github.com/terraform-providers/terraform-provider-datadog/pull/122, trying to push internally for adding update capabilities to the Datadog API (see https://github.com/zorkian/go-datadog-api/pull/162#issuecomment-401940257 for context) but no ETA so far.

**Comment by masci** [comment]
Feature released with 1.6.0
