### ISSUE TITLE
Support for "process" timeboards.

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-datadog#77]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.8.0
+ provider.datadog v1.0.3
```

### Affected Resource(s)

- https://www.terraform.io/docs/providers/datadog/r/timeboard.html

### Terraform Configuration Files

Trying to take the JSON config from a dashboard I created in Datadog, and port it to HCL so that I can manage it with Terraform. It appears that the _process visualization_ is not supported yet by this provider.

The HCL config for Datadog is:

```hcl
resource "datadog_timeboard" "processes_nonprod" {
    title       = "Processes (Non-Prod)"
    description = "A view of host processes."
    read_only   = true

    graph {
        title     = "CPU (total) per process"
        viz       = "process"
        autoscale = true
        status    = "done"

        request {
            type        = "process"
            metric      = "process.stat.cpu.total_pct.norm"
            text_filter = "sshd"
            limit       = 200
            tag_filters = [
              "$account",
              "$cluster"
            ]

            style {
                palette = "classic"
                type    = "solid"
                width   = "normal"
            }

            notes = ""
        }
    }

    template_variable {
        name    = "account"
        prefix  = "account"
        default = "REDACTED"
    }

    template_variable {
        name    = "cluster"
        prefix  = "cluster"
        default = "REDACTED"
    }
}
```

See https://docs.datadoghq.com/integrations/process/

**Comment by nmuesch** [comment]
Hey @skyzyx Thanks for the issue report and sorry for the delay here! I just wanted to comment to let you know we released version 2.1.0 of the Datadog Terraform Provider last week that includes support for the new Dashboard resource. With this new resource, we've added support for creating `process_query` widgets. Here is an example:

```

resource "datadog_dashboard" "process_graph_dash" {
  title         = "Process Widget Example"
  description   = "Created using the Datadog provider in Terraform"
  layout_type   = "ordered"
  is_read_only  = true

  widget {
    timeseries_definition {
      request {
        process_query {
          metric = "process.stat.cpu.total_pct"
          search_by = "error"
          filter_by = ["active"]
          limit = 50
        }
        display_type = "area"
      }
    }
  }
}
```

More information about this can be found in the provider documentation for this resource - https://www.terraform.io/docs/providers/datadog/r/dashboard.html#nested-process_query-blocks

I'll go ahead and close this issue for now, but please do let me know if you hit any further issues with this!

**Comment by skyzyx** [comment]
Thanks, @nmuesch! Looking forward to digging into this soon! A couple of follow-up questions:

1. Are these _live processes_? _Process checks_? Both?

1. I've been filling this gap with custom code and the Python SDK in the interim while waiting for this support. The API, unfortunately, doesn't support updates, so the changes with the Python SDK were not idempotent. With this functionality in Terraform now, is this change idempotent?

**Comment by nmuesch** [comment]
Hey, happy to help answer these. 

1) These are live processes. The process check emits standard metrics that you should be able to directly map onto any other widget type (you can see the emitted metrics for that check here - https://docs.datadoghq.com/integrations/process/#metrics)

2) Could you elaborate on this a bit? Are you referring to updates on the dashboard itself? The Terraform Provider will do individual update operations between each terraform apply (feel free to check out the code here if that helps - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L85)

Let me know if that addresses your questions 😄

**Comment by skyzyx** [comment]
> Could you elaborate on this a bit? Are you referring to updates on the dashboard itself? The Terraform Provider will do individual update operations between each terraform apply (feel free to check out the code here if that helps - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L85)

Sorry. I think I'm conflating multiple things.

I use the Datadog Python SDK to fill the gaps that previously existed in the _Datadog provider for Terraform_. Today (and until I update my code with the just-released changes), I use the Python SDK to create three sets of resources in Datadog.

1. Timeboards — I generate a stub timeboard with Terraform, then use Python to check `terraform output` to lookup the dashboard ID, then hit the API endpoint to update the stub dashboard with the correct data that I care about. (It sounds like this was the piece that was recently added to the _Datadog provider for Terraform_.)

1. Live process _monitors_ — Our internal SRE teams use _live process monitors_ to ensure that the processes that need to be running on the boxes are running. The Datadog API for this does not support an _update_ operation, and is therefore non-idempotent. If I want to push updates, I need to delete them first, then push the new set.

1. Process check _monitors_ — We have an external vendor who provides some System Engineering and Monitoring services and they use _process check monitors_ to ensure that the processes that need to be running on the boxes are running. The Datadog API for this does not support an _update_ operation, and is therefore non-idempotent. If I want to push updates, I need to delete them first, then push the new set.

Now that I'm re-reading my initial request, this appears to be a request for (a) processes displayed on (b) timeboards. Which leads to a follow-up question:

Does the new functionality empower me to use Terraform to create process-related _monitors_? Or do I still need to hang on to my custom code using the Datadog Python SDK for this? If the latter is the case, should I open a _new ticket_ specifically for the monitoring portion of my request?

Thanks, again!

**Comment by nmuesch** [comment]
Hey, thanks for the extra context here! The monitors resource in this provider indeed allows you to setup a monitor for live processes data. I've created a PR here - https://github.com/terraform-providers/terraform-provider-datadog/pull/273/files that contains an example of what such a config would look like. (The monitor UI also has an `Export` button that'll help show the value for the query should you create this or an example in the UI first)
