### ISSUE TITLE
Timeboard Host Map visualization type Containers

### ISSUE THREAD

**Issue by angelikatyborska** [terraform-providers/terraform-provider-datadog#89]
By default, all Host Map visualizations are of type "Hosts". There is a second type, "Containers".  I would like to be able to explicitly choose one of those types. Currently I have found no way to create a "Containers" Host Map via Terraform.

![screen shot 2018-09-04 at 16 11 36](https://user-images.githubusercontent.com/7852553/45036764-a87cd300-b05d-11e8-8459-966b3382f7b3.png)

**Comment by therve** [comment]
Starting with #106 you can now specify the node_type to "container".
