### ISSUE TITLE
Deprecation warning for is_admin attribute while alternative access_role is not yet available

### ISSUE THREAD

**Issue by miguelaferreira** [terraform-providers/terraform-provider-datadog#95]
The provider documentation does not mention the `is_admin` attribute as being deprecated, while terraform clearly warns about this. Also terraform mentions that the replacement of `is_admin` is `access_role` but that attribute is both undocumented and not accepted by terraform.

### Terraform Version
```
Terraform v0.11.8
+ provider.datadog v1.2.0
```

### Affected Resource(s)
- datadog_user

### Terraform Configuration Files
```hcl
provider "datadog" {
  api_key = "${var.datadog_api_key}"
  app_key = "${var.datadog_app_key}"
}

resource "datadog_user" "user1" {
  email  = "user1@mail.com"
  handle = "user1@mail.com"
  name   = "User One"
  is_admin = true
}

resource "datadog_user" "user2" {
  email  = "user2@mail.com"
  handle = "user2@mail.com"
  name   = "User Two"
  access_role = "admin"
}
```

### Expected Behavior
Provider documentation should reflect the deprecated status of `id_admin` and document the alternative attribute `access_role`, and it should be possible to use `access_role`.
Therefore, terraform should print the deprecation warning and accept the `access_role` attribute.

### Actual Behavior
Terraform prints a warning about deprecation of `is_admin` and an error about the `access_role`

```
(...)
Warning: datadog_user.user1: "is_admin": [DEPRECATED] This parameter will be replaced by `access_role` and will be removed from the next Major version
Error: datadog_user.user2: : invalid or unknown key: access_role
(...)
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by masci** [comment]
My bad, I'm adding support for `user_role` and the transition is taking more time than I wanted, also I forgot to update the docs mentioning `is_admin` deprecation so this is got even more confusing.

Unfortunately, providing suppor for both `is_admin` and `user_role` at the same time proved to be extremely difficult so this is now the roadmap to add `user_role`:
1) deprecate `is_admin` (done)
2) add `user_role` and remove `is_admin` at the same time, release the change with a major

**Comment by masci** [comment]
@miguelaferreira Correct, for a number of reasons more related to how the Datadog API works than terraform itself, I wasn't able to make the two options coexist. The change will be delivered with a major release so it should be relatively safe, I'll try to keep communications loud and clear about that.
